- .circleci/common.yml
- infrastructure/annotations-api/src/main.ts
- infrastructure/fxa-webhook-proxy/src/main.ts
- infrastructure/image-api/src/main.ts
- infrastructure/parser-graphql-wrapper/src/main.ts
- infrastructure/pocket-router/src/main.ts
- infrastructure/shared-snowplow-consumer/src/main.ts
- infrastructure/transactional-emails/src/main.ts
- infrastructure/user-api/src/main.ts
Because we were using a non-default state, terraform was setting a prefix for the s3 backend to something like `env:/Prod/pocket-router` for the pocket-router. Then because of the different run contexts, etc. it was not pulling the correct state file.
We are going to remove the cloud backend, and the naming/account compartmentalization of the s3 buckets for the state files obviates the need for workspace. This change builds the workspace directly in cdktf vs. relying on the environment variable, so that we can do both the s3 and cloud backends without any additional changes.
> fix(tf): build prefix for workspace to avoid TF_WORKSPACE variable use

- infrastructure/client-api/src/main.ts
We set it to an hour to give us more validation time, set it to 5 minutes now.
> chore(client-api): set blue/green task set termination to 5 mins

- renovate.json
* Disable pinning of docker-compose digests, we want that to pull native architecture images for development so those on M1's dont have to emulate x64
* Get opentelemetry and any other monorepos grouped together.
> chore(deps): make renovate group & not digest docker-compose

- servers/list-api/src/config/index.ts
- servers/list-api/src/test/graphql/mutations/savedItemsMutationService-delete.integration.ts
List API used to old deletion queues for list, however that is no longer the case, removing configs to reduce confusion
> chore(config): removing old config options from list

- servers/client-api/config/router.yaml
to help in debugging collection API scaling/performance issues by viewing arguments being sent to the queries being called at high volume.
> feat: expose public collection api query vars in studio

- servers/annotations-api/src/dataservices/highlights.ts
- servers/annotations-api/src/test/mutation/highlights-batchwrite.integration.ts
- servers/annotations-api/src/test/mutation/highlights-create.integration.ts
- servers/annotations-api/src/test/query/highlights-fixtures.ts
Annotations api had some flakey tests that were inhibiting prs and causing us to re-run them 
https://mozilla-hub.atlassian.net/browse/POCKET-9477
This was causing 2 calls to the logAnnotationMutation that was hit intermittently based on what tests ran before  the batch tests. I got the test to always fail by adding users_meta to the seed list which caused a duplicate key error on every run. 
It seems that something about how a transaction runs it wasnt always deleting the old value first if logAnnotationMutation was called multiple times. I fixed this by only calling it once from the batch call, and making other calls conditional.
For some reason the createHighlight test had issues with Jest.fake timers unless I called setSystemTime.. no idea why. but in local testing this worked
> fix(annotations-api): fixing flakey annotations tests

- infrastructure/list-api/src/main.ts
Saw I forgot to turn off list-api use codepipeline and it was causing terraform to think a destroy was needed instead of a replace (service was still deploying just fine though)
> fix(list-api): switching off list-api codepipeline

- Dockerfile
- pnpm-lock.yaml
- servers/shareable-lists-api/package.json
Get prisma to work with our deployment.
Once prisma was in, also got an error with `keyv` missing. It likely worked locally cause its being hoisted accidentaly or something..
> fix(prisma): add cp to after prunning

- packages/terraform-modules/package.json
I noticed that the terraform modules was synth'ing during terraform plans/apply cause it had a synth script defined. This just renames it to avoid that conflict.
> fix(terraform-modules): ensuring that the modules does not synth

- servers/client-api/rhai/claims_forwarding.rhai
Our downstream services, like user-api, expect
to receive undefined and not empty strings.
> fix(client-api): do not set headers to empty string

- servers/shareable-lists-api/prisma/migrations/20240124212856_item_unique_per_list/migration.sql
- servers/shareable-lists-api/prisma/schema.prisma
Only allow an itemId to appear once per list.
Would be preferable to use a generated column
which contains the URL hash, but prisma does not
support this feature.
> feat(shareablelists): uniquenes logic in db model

- servers/shareable-lists-api/prisma/migrations/20240124225016_db_default_uuid/migration.sql
- servers/shareable-lists-api/prisma/schema.prisma
Avoid relying on prisma, so that we are not
locked into the ORM.
> fix(shareablelists): use db for uuid generation

- infrastructure/account-data-deleter/src/config/index.ts
- infrastructure/account-data-deleter/src/dataDeleterApp.ts
- infrastructure/annotations-api/src/config/index.ts
- infrastructure/annotations-api/src/main.ts
- infrastructure/client-api/src/config/index.ts
- infrastructure/client-api/src/main.ts
- infrastructure/feature-flags/src/config/index.ts
- infrastructure/feature-flags/src/main.ts
- infrastructure/image-api/src/config/index.ts
- infrastructure/image-api/src/main.ts
- infrastructure/list-api/src/config/index.ts
- infrastructure/list-api/src/main.ts
- infrastructure/parser-graphql-wrapper/src/config/index.ts
- infrastructure/parser-graphql-wrapper/src/main.ts
- infrastructure/shareable-lists-api/src/config/index.ts
- infrastructure/shareable-lists-api/src/main.ts
- infrastructure/shared-snowplow-consumer/src/config/index.ts
- infrastructure/shared-snowplow-consumer/src/sharedSnowplowConsumerApp.ts
- infrastructure/transactional-emails/src/transactionalEmailSQSLambda.ts
- infrastructure/user-api/src/config/index.ts
- infrastructure/user-api/src/main.ts
- packages/terraform-modules/src/base/ApplicationECSContainerDefinition.ts
- packages/terraform-modules/src/base/ApplicationECSService.spec.ts
- packages/terraform-modules/src/base/ApplicationECSService.ts
- packages/terraform-modules/src/base/__snapshots__/ApplicationECSService.spec.ts.snap
- packages/terraform-modules/src/pocket/__snapshots__/PocketALBApplication.spec.ts.snap
- packages/terraform-modules/src/pocket/__snapshots__/PocketECSApplication.spec.ts.snap
I noticed that our task definitions were always set to the `latest` image. This would mean that if a scaling event occurred during a deployment or after a failed deploy, the tasks would not pull the correct currently "live" image. This change ensures that the task defintion always is pointing to a specific sha tag of the docker image.
> fix(sha1): specifiying the git sha1 in the task definition

- servers/list-api/schema.graphql
- servers/list-api/src/businessEvents/types.ts
- servers/list-api/src/dataService/savedItemsService.ts
- servers/list-api/src/models/SavedItem.ts
- servers/list-api/src/resolvers/index.ts
- servers/list-api/src/test/graphql/mutations/savedItem/savedItemUpdateTitle.integration.ts
Mutation to update the title of a save. Just updates the user's personal save -- not the global metadata for the item stored by the parser.
Emits a new event for the updated title (analytics will need to integrate if they want to use)
> feat(list): enable users to update title of a save

- servers/parser-graphql-wrapper/src/resolvers.ts
- these errors would be from the parser, which we do not want impacting any clients. this field is nullable on CorpusItem, so returning null on error works
> fix: swallow CorpusItem.timeToRead resolver errors

- servers/annotations-api/src/dataservices/highlights.ts
Fix the tests in annotations api, but ensuring that we await the transactions to complete. 
This was not a user facing bug because when ran through Apollo, it waits for the event loop to complete.
> fix(annotation-api): updating the annotations transactions to await

- servers/parser-graphql-wrapper/src/dataLoaders/itemLoader.ts
- servers/parser-graphql-wrapper/src/refreshMutation.integration.ts
- servers/parser-graphql-wrapper/src/resolvers.ts
I played with adding a refresh call to web-client and noticed that the refresh mutation was not clearing the dataloader cache and so that was returning stale data still.
> fix(cache): clear dataloader cache on refresh

- infrastructure/account-data-deleter/src/dataDeleterApp.ts
- packages/feature-flags-client/src/index.spec.ts
- packages/feature-flags-client/src/index.ts
- packages/feature-flags-client/src/mockClient.ts
- pnpm-lock.yaml
- servers/account-data-deleter/package.json
- servers/account-data-deleter/src/batchDeleteHandler.spec.ts
- servers/account-data-deleter/src/batchDeleteHandler.ts
- servers/account-data-deleter/src/config/index.ts
- servers/account-data-deleter/src/server.ts
- servers/account-data-deleter/src/unleash.ts
Add unleash client to account-data-deleter. Do not poll for messages if the killswitch is on, to enable turning the delete logic on/off.
The unleash client refreshes toggles once per minute. 
Feature flags are created in prod and dev.
> feat(ADD): add feature flags killswitch to poll logic

- infrastructure/annotations-api/src/main.ts
I noticed that we had xray errors in AWS for the annotations api due to missing xray permissions
```
2024-02-08T01:39:47.601Z error exporterhelper/common.go:174 Exporting failed. Rejecting data. {"kind": "exporter", "data_type": "traces", "name": "awsxray", "error": "Permanent error: AccessDeniedException: User: arn:aws:sts::sdasdasd:assumed-role/AnnotationsAPI-Prod-TaskRole/asdasdasdasd is not authorized to perform: xray:PutTraceSegments because no identity-based policy allows the xray:PutTraceSegments action\n\tstatus code: 403, request id: asdasdasdasd", "rejected_items": 224} 
```
> fix(xray): adding xray to annotations api

- servers/parser-graphql-wrapper/src/database/mysql.ts
- servers/parser-graphql-wrapper/src/resolvers.spec.ts
- servers/parser-graphql-wrapper/src/resolvers.ts
- servers/parser-graphql-wrapper/src/shortUrl/shortUrl.integration.ts
- servers/parser-graphql-wrapper/src/shortUrl/shortUrl.spec.ts
- servers/parser-graphql-wrapper/src/shortUrl/shortUrl.ts
Adds ability to resolve an Item entity from a short Pocket Share URL. The Pocket Share URL is created on request and redirects to the original page (currently controlled by Web repo).
[POCKET-9547]
[POCKET-9547]: https://mozilla-hub.atlassian.net/browse/POCKET-9547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(parser): resolve item from short url

- infrastructure/image-api/src/main.ts
- infrastructure/parser-graphql-wrapper/src/main.ts
- packages/terraform-modules/src/base/ApplicationElasticacheCluster.ts
- packages/terraform-modules/src/base/ApplicationMemcache.ts
- packages/terraform-modules/src/base/ApplicationRedis.ts
- packages/terraform-modules/src/base/ApplicationServerlessRedis.spec.ts
- packages/terraform-modules/src/base/ApplicationServerlessRedis.ts
- packages/terraform-modules/src/base/__snapshots__/ApplicationServerlessRedis.spec.ts.snap
- packages/terraform-modules/src/index.ts
Enable support for AWS Serverless Elasticache, starting with Redis for our use case.
Subsequently, switch Parser and Image api to the new redis
https://mozilla-hub.atlassian.net/browse/POCKET-9588
>  feat(serverless-redis): adding in support for the serverless redis cache

- infrastructure/image-api/src/main.ts
- infrastructure/parser-graphql-wrapper/src/main.ts
Something is wrong with the serverless cache, reverting the endpoints for now
> fix(cache): revert serverless for now

- infrastructure/image-api/src/main.ts
- infrastructure/parser-graphql-wrapper/src/main.ts
- pnpm-lock.yaml
- servers/image-api/package.json
- servers/image-api/src/cache/index.ts
- servers/image-api/src/config/index.ts
- servers/image-api/src/server/apollo.ts
- servers/parser-graphql-wrapper/package.json
- servers/parser-graphql-wrapper/src/cache/index.ts
- servers/parser-graphql-wrapper/src/config/index.ts
- servers/parser-graphql-wrapper/src/server.ts
- servers/shareable-lists-api/package.json
Get serverless redis working by supporting cluster mode in the client which is used by AWS Serverless Redis.
In a followup, need to ensure that if redis is down, or we can't connect that it fails silently to the user.
Followups
* https://mozilla-hub.atlassian.net/browse/POCKET-9599
* https://mozilla-hub.atlassian.net/browse/POCKET-9600
> fix(redis): enabling cluster support for serverless

- packages/terraform-modules/src/base/ApplicationServerlessRedis.ts
Ensure that we use the lowercase cache name... otherwise terraform tries to recreate it.
> fix(name): ensuring that the same name is always used for cache

- servers/client-api/config/router.yaml
The introspection query used by our codegen library has > 200 height.
https://github.com/graphql/graphql-js/blob/main/src/utilities/getIntrospectionQuery.ts\#L131-L170
Bump the height restriction to accomodate.
> fix(client): bump router max height limit

- packages/apollo-utils/src/sentry/initSentry.ts
Sentry by default truncates messages/values to 250 characters https://docs.sentry.io/platforms/node/configuration/options/#max-value-length
> fix(sentry): ensure sentry does not truncate values

- infrastructure/shareable-lists-api/src/main.ts
Looks like a minor upgrade auto occured on AWS, so matching the version in the infra code.
> fix(shareable-lists): matching version

- infrastructure/parser-graphql-wrapper/src/main.ts
- servers/parser-graphql-wrapper/src/config/index.ts
There is a bug in terraform for adjusting serverless cache usage. So for now we can sidestep by reducing the TTL.
> fix(cache-size): limit our cache size by reducing age

- packages/tracing/src/tracing.ts
Make sure that we have low enough export values that allow all traces to export to otel without filling up the queue.
Before this change BatchSpan was only exporting spans every 5sec and its queue was filling up and discarding data.
> fix(spans): decreasing the time between exporting span traces

- servers/user-list-search/schema.graphql
- servers/user-list-search/src/datasource/SavedItemsDataSource.ts
- servers/user-list-search/src/datasource/elasticsearch/Paginator.ts
- servers/user-list-search/src/datasource/elasticsearch/elasticsearchSearch.ts
- servers/user-list-search/src/freeSearch.integration.ts
- servers/user-list-search/src/freeSearchByOffset.integration.ts
- servers/user-list-search/src/premiumSearch.integration.ts
- servers/user-list-search/src/premiumSearchByOffset.integration.ts
- servers/user-list-search/src/types.ts
Supports v3 proxy response which includes what kind of search was performed.
Alternative considered: request the user's premium status as part of the response and infer what kind of search was done based on that.
Didn't do this because 
* it would add a dependency for another subgraph (User), making this search API less robust
* avoid coding derivative business logic in multiple places; better to stay close to the source
[POCKET-9630]
[POCKET-9630]: https://mozilla-hub.atlassian.net/browse/POCKET-9630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(search): add searchType to graph

- servers/user-list-search/schema.graphql
- servers/user-list-search/src/datasource/SavedItemsDataSource.ts
- servers/user-list-search/src/datasource/elasticsearch/Paginator.ts
- servers/user-list-search/src/datasource/elasticsearch/elasticsearchSearch.ts
- servers/user-list-search/src/freeSearch.integration.ts
- servers/user-list-search/src/freeSearchByOffset.integration.ts
- servers/user-list-search/src/premiumSearch.integration.ts
- servers/user-list-search/src/premiumSearchByOffset.integration.ts
- servers/user-list-search/src/types.ts
This reverts commit bffde026e23c7a05c9c058de0d7082cc3c8b5f27.
Turns out this supports an undocumented and unused response in /v3/get, so let's not clutter our graph.
> Revert "feat(search): add searchType to graph (#264)"

- servers/v3-proxy-api/src/graph/get/toGraphQL.spec.ts
- servers/v3-proxy-api/src/graph/get/toGraphQL.ts
- servers/v3-proxy-api/src/routes/v3Get.ts
Do not pass an empty filters object (graphql is rejecting it), instead only add filters to the variables if they are relevant.
Fix a bug where the Simple transformer was being called when it should have been the Complete transformer.
> fix(v3proxy): fix filters and total+complete response

- servers/user-list-search/src/datasource/SavedItemsDataSource.ts
- servers/user-list-search/src/freeSearch.integration.ts
- servers/user-list-search/src/freeSearchByOffset.integration.ts
The resolved_title (items_extended.title) field is not case-insensitive in the database. Lowercase it for searching, and also lowercase the search term just in case. in case.
[POCKET-9723]
[POCKET-9723]: https://mozilla-hub.atlassian.net/browse/POCKET-9723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(search): case-insensitive search for fallback title

- servers/user-list-search/src/datasource/SavedItemsDataSource.ts
- servers/user-list-search/src/freeSearch.integration.ts
- servers/user-list-search/src/freeSearchByOffset.integration.ts
Add domain filter to free tier search. This aligns current behavior with /v3 free-tier search behavior.
[POCKET-9726]
[POCKET-9726]: https://mozilla-hub.atlassian.net/browse/POCKET-9726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(search): add domain filter to free tier search

- servers/v3-proxy-api/src/graph/get/toRest.spec.ts
- servers/v3-proxy-api/src/graph/get/toRest.ts
- servers/v3-proxy-api/src/graph/types.ts
- servers/v3-proxy-api/src/routes/v3Fetch.ts
- servers/v3-proxy-api/src/test/fixtures/fetch.ts
- servers/v3-proxy-api/src/test/fixtures/fixtures.ts
- servers/v3-proxy-api/src/test/fixtures/get-search.ts
- servers/v3-proxy-api/src/test/fixtures/get.ts
Add the top level response fields into the v3 rest response like:
* status
* complete
* error
* maxActions
* since
https://mozilla-hub.atlassian.net/browse/POCKET-9725
This does not implement `error` codes or `complete` fully. we will followup with those
> feat(toplevel): adding in the toplevel v3 responses

- servers/v3-proxy-api/src/main.ts
Make sentry not truncate errors.
This is a copy paste of the sentry init from apollo-utils, but i didnt want to use that just yet because then that would make v3 proxy include apollo stuff which is not needed atm.
> fix(sentry): ensuring that we do not truncate sentry

- .circleci/common.yml
- .circleci/config.yml
- package.json
- pnpm-lock.yaml
**JQ**
When updating the JQ circleci plugin it looks like the install step changes how the subsequent steps run. e now include JQ in our build image, so we can just remove this instead.
**aws**
Looks like the latest aws update changes some things with smithy. See https://github.com/aws/aws-sdk-js-v3/issues/5435 
https://pocket.sentry.io/issues/5070670422/?project=6410738&query=is:unresolved&statsPeriod=14d&stream_index=0
**ci**
also ensuring that the CI always runs if we change common ci files
> fix(jq-aws): fixing a jq & aws update

- package.json
- pnpm-lock.yaml
Cleans up remnants of https://github.com/Pocket/pocket-monorepo/pull/311 and https://github.com/Pocket/pocket-monorepo/pull/309
Basically we had errors because we had multiple versions of the AWS SDK which had multiple library versions.
It seems like what happened is AWS released versions of the monorepo at different points throughout the day, so the aws sdk versions got out of sync.
Now that we are in sync, we can fix this.
> fix(aws): ensuring aws consistency

- servers/v3-proxy-api/src/graph/graphQLClient.ts
- servers/v3-proxy-api/src/routes/ActionsRouter.ts
- servers/v3-proxy-api/src/routes/v3Add.ts
- servers/v3-proxy-api/src/routes/v3Send.integration.ts
- servers/v3-proxy-api/src/routes/v3Send.ts
- servers/v3-proxy-api/src/routes/validations/SendSchema.ts
Add/readd actions on the v3/send endpoint.
Implementing add/readd by item_id is ticketed in Pocket-9805 (not available in the graph, seems also a weird use case but... whatever)
[POCKET-9624]
[POCKET-9624]: https://mozilla-hub.atlassian.net/browse/POCKET-9624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(v3proxy/send): implement add/readd

- servers/account-data-deleter/src/batchDeleteHandler.ts
I noticed an SQS queue was building up, this adds some logs for debugging purposes.
> fix(account-deleter): adding in logging for account deleter poller

- .circleci/common.yml
- .circleci/repo-jobs.yml
- README.md
- infrastructure/account-data-deleter/package.json
- infrastructure/account-delete-monitor/package.json
- infrastructure/annotations-api/package.json
- infrastructure/braze/package.json
- infrastructure/client-api/package.json
- infrastructure/feature-flags/package.json
- infrastructure/fxa-webhook-proxy/package.json
- infrastructure/image-api/package.json
- infrastructure/list-api/package.json
- infrastructure/parser-graphql-wrapper/package.json
- infrastructure/pocket-event-bridge/package.json
- infrastructure/push-server/package.json
- infrastructure/sendgrid-data/package.json
- infrastructure/shareable-lists-api/package.json
- infrastructure/shared-snowplow-consumer/package.json
- infrastructure/transactional-emails/package.json
- infrastructure/user-api/package.json
- infrastructure/v3-proxy-api/package.json
- servers/push-server/package.json
- turbo.json
Optimize turbo repo so that at least locally we are only building/processing things that actually changed.
This does the following:
* Changes the test/test-integration/lint/format jobs to only need `prebuild` and not `build` which was buiilding all the code unnecessarily
* Removed the concurrency limit on `lint` in CI, still need it on `test` due to OOM in terraform-modules...
* Adds a cache step to pnpm in circleci
* Adds all the possible inputs and outputs to each turbo repo job to calculate cache hashes
* Adds `NODE_ENV` to turbo repo so that its value is considered for all job cache hashes
* Removes just echo tests
What this pr does not do and will be in followup:
* restore and save off the turbo repo cache. This may take some work, or for us to buy [Vercel's remote …
> chore(turbo): make turbo repo performant based on inputs and outputs

- .syncpackrc
- pnpm-lock.yaml
`@aws-sdk` seems to release their monorepo packages at different times. This can cause our aws-sdk packages to get our of version sync which always causes issues.
This utilizes Syncpack to fail a CI check if aws-sdk packages are not the same version https://jamiemason.github.io/syncpack/examples/fix-aws-sdk-version-mismatch/
Also added a few more rules from the syncpack examples like:
* ensuring types always are in devDepedencies
* ensuring node engines always match
> fix(aws): ensure that aws-sdk packages always have the same version

- package.json
- pnpm-lock.yaml
- servers/push-server/package.json
- servers/push-server/src/apns.ts
node-apns is deprecated and not maintained anymore. Furthermore it has security vulnerabilities in the underlying node-forge library.
This upgrades us to the latest apns2 library that is used in the community, most things are all a 1:1 since the APNS api is not any different just library.
> fix(apns2): upgrading to APNS2

- .circleci/account-data-deleter.yml
- .circleci/account-delete-monitor.yml
- .circleci/annotations-api.yml
- .circleci/common.yml
- .circleci/feature-flags.yml
- .circleci/fxa-webhook-proxy.yml
- .circleci/image-api.yml
- .circleci/list-api.yml
- .circleci/parser-graphql-wrapper.yml
- .circleci/push-server.yml
- .circleci/sendgrid-data.yml
- .circleci/shareable-lists-api.yml
- .circleci/shared-snowplow-consumer.yml
- .circleci/transactional-emails.yml
- .circleci/user-api.yml
- .circleci/user-list-search.yml
- .circleci/v3-proxy-api.yml
Lambda's used to rely on CircleCI pushing parameters to SSM.  With our new deploy setup these are no longer needed since CodeDeploy will set these when needed.
> chore(cleanup): removing deploy params

- servers/list-api/schema.graphql
- servers/list-api/src/dataService/tagDataService.ts
- servers/list-api/src/models/SavedItem.ts
- servers/list-api/src/models/tag.ts
- servers/list-api/src/resolvers/index.ts
- servers/list-api/src/resolvers/mutation.ts
- servers/list-api/src/resolvers/utils.spec.ts
- servers/list-api/src/resolvers/utils.ts
- servers/list-api/src/test/graphql/mutations/clearTags.integration.ts
- servers/list-api/src/test/graphql/mutations/replaceTags.integration.ts
- servers/list-api/src/test/graphql/mutations/tagsByName/deleteTagByName.integration.ts
- servers/list-api/src/test/graphql/mutations/tagsByName/removeTagsByName.integration.ts
- servers/list-api/src/test/graphql/mutations/tagsByName/renameTagByName.integration.ts
- servers/list-api/src/types/index.ts
To support v3 proxy /send endpoint, which can identify a SavedItem either by URL or ID interchangeably, and uses tag names instead of tag IDs.
Adds:
* clearTags - clear all tags from a saved item referenced by id or url
* renameTagByName - rename a tag by its name (not id)
* deleteTagByName - delete a tag by its name (not id)
* removeTagsByName - remove tags from a saved item by names, not ids; saveditem referenced by id or url
* replaceTags - replace all tags on a saved item referenced by id or url
> feat(list): add tag mutations accessed by name

- infrastructure/feature-flags/src/main.ts
- scripts/convert-auroraV1-to-V2-postgres.sh
Postgres 13 (current db for Feature Flags) will be EOL and incurring extra AWS charges this month.
This converts it to Postgres 16 and will move it to serverless V2. 
The script has already been ran on Dev and after it was run, all we needed to do was import the new serverless instance.
```
terraform import aws_rds_cluster_instance.rds_rds-instance_6675FA88 featureflags-dev-serverless
```
1. Block all merges to `main`
2. Execute convert script.
3. Execute Blue-Green cutover
4. Delete extra reader instance that our conversion created.
5. Synth the state locally, and import the serverless instance into terraform
6. Merge the pr to `main`
7. Destroy the blue green deployment
8. Destroy the old blue cluster
In testing there is at most 10 seconds of downtime for the feature flag service during …
> chore(upgrade): upgrading feature flag database

- infrastructure/shareable-lists-api/src/main.ts
- packages/terraform-modules/src/base/ApplicationRDSCluster.ts
- packages/terraform-modules/src/base/__snapshots__/ApplicationRDSCluster.spec.ts.snap
Upgrade Shareabelist database for 2 reasons:
* There is a new Aurora version
* We need to blue/green deploy to update the RDS certificate which expires in August.
This PR will be a no-op pr when done. The actual update will be done via a click ops bluegreen deploy.
> fix(db): upgrade shareablelists db

- servers/parser-graphql-wrapper/schema.graphql
- servers/parser-graphql-wrapper/src/dataLoaders/itemLoader.ts
- servers/parser-graphql-wrapper/src/listen/ListenModel.spec.ts
- servers/parser-graphql-wrapper/src/listen/ListenModel.ts
- servers/parser-graphql-wrapper/src/model.ts
Pull the estimated words per minute constant value from web repo, and estimate listen duration based on word count of article body.
[POCKET-9647]
[POCKET-9647]: https://mozilla-hub.atlassian.net/browse/POCKET-9647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(parser:listen): add listen duration estimate

- servers/v3-proxy-api/src/errors/InvalidActionError.ts
- servers/v3-proxy-api/src/routes/ActionsRouter.ts
- servers/v3-proxy-api/src/routes/v3Send.integration.ts
- servers/v3-proxy-api/src/routes/validations/SendActionValidators.ts
- servers/v3-proxy-api/src/routes/validations/SendSchema.ts
Rather than rejecting requests that contain unsupported send actions, treat them as though they returned errors.
To support android client which sends actions that are no longer used, but we don't want the API to reject.
[POCKET-9822]
[POCKET-9822]: https://mozilla-hub.atlassian.net/browse/POCKET-9822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(v3proxy:send): return error data for invalid /send actions

- .syncpackrc
Content folks just hit a bug where sentry was not the same version across the repo. 
This should ensure that we don't encounter this.
> fix(sentry): ensure sentry is always same version

- servers/v3-proxy-api/src/routes/v3Send.integration.ts
- servers/v3-proxy-api/src/routes/v3Send.ts
- servers/v3-proxy-api/src/routes/validations/SendSchema.ts
Android sends URI-encoded stringified JSON actions to v3/send via GET verb. This update validates and parses this string and serializes it correctly into actions array.
[POCKET-9822]
[POCKET-9822]: https://mozilla-hub.atlassian.net/browse/POCKET-9822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(v3proxy:send): parse send request actions

- servers/v3-proxy-api/src/routes/v3Send.integration.ts
- servers/v3-proxy-api/src/routes/validations/SendSchema.ts
- servers/v3-proxy-api/src/server.ts
Add urlencoded middleware to decode x-www-urlencoded bodies.
Explicitly decode actions string into JSON from url-encoded string, similar to GET.
[POCKET-9822]
[POCKET-9822]: https://mozilla-hub.atlassian.net/browse/POCKET-9822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(v3proxy:send): decode encoded actions array in post body

- infrastructure/image-api/src/config/index.ts
- infrastructure/image-api/src/main.ts
- infrastructure/list-api/src/config/index.ts
- infrastructure/list-api/src/main.ts
- infrastructure/parser-graphql-wrapper/src/config/index.ts
- infrastructure/parser-graphql-wrapper/src/main.ts
- infrastructure/shareable-lists-api/src/config/index.ts
- infrastructure/shareable-lists-api/src/main.ts
- infrastructure/shared-snowplow-consumer/src/config/index.ts
- infrastructure/shared-snowplow-consumer/src/sharedSnowplowConsumerApp.ts
- infrastructure/user-api/src/config/index.ts
- infrastructure/user-api/src/main.ts
- infrastructure/v3-proxy-api/src/config/index.ts
- infrastructure/v3-proxy-api/src/main.ts
As we roll out the v3-proxy we want as much observability as possible to mitigate any issues.
This enables dumping alb logs to our S3 bucket that can be piped into Athena or Snowflake for quick querying and analysis.
> fix(alb): adding in alb access logs

- servers/v3-proxy-api/src/graph/get/toRest.ts
- servers/v3-proxy-api/src/routes/v3Fetch.integration.ts
- servers/v3-proxy-api/src/routes/v3Fetch.ts
- servers/v3-proxy-api/src/routes/validations/FetchSchema.ts
This is possible on the current /v3/fetch endpoint but was previously only implemented on /v3/get on the proxy.
> feat(v3proxy): enable requesting annotations on fetch

- packages/apollo-utils/src/sentry/apolloSentryPlugin.ts
- servers/parser-graphql-wrapper/src/dataLoaders/articleLoader.ts
- servers/parser-graphql-wrapper/src/dataLoaders/itemLoader.ts
Our logs are filled with unhelpful stack traces that provide too much data.
This removes the stack from the server logs.
Separately we need some more data on the parser to better debug issues we are currently seeing.
> fix(errors): cleanup the error logs

- servers/v3-proxy-api/src/routes/v3Get.integration.ts
- servers/v3-proxy-api/src/routes/validations/GetSchema.ts
Existing android versions sometimes pass search term that is empty (not intending to search, just there)
[POCKET-9898]
[POCKET-9898]: https://mozilla-hub.atlassian.net/browse/POCKET-9898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(v3proxy:search): ignore empty search term instead of rejecting query

- servers/list-api/schema.graphql
- servers/list-api/src/dataService/tagDataService.ts
- servers/list-api/src/dataService/usersMetaService.ts
- servers/list-api/src/models/tag.ts
- servers/list-api/src/resolvers/index.ts
- servers/list-api/src/test/graphql/queries/tagsList.integration.ts
I don't like doing stuff like this but I'd rather have it separate than provide an unpaginated way to potentially retrieve every saved item connection.
[POCKET-9913]
[POCKET-9913]: https://mozilla-hub.atlassian.net/browse/POCKET-9913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(list:tagslist): support v3 tag list query

- servers/v3-proxy-api/src/routes/v3Get.integration.ts
- servers/v3-proxy-api/src/routes/validations/GetSchema.ts
Allow android requests on get for shortest and longest sort order to succeed
> fix(sort): adding in longest and shortest sort no-op

- .syncpackrc
- packages/lambda-secrets/package.json
- packages/lambda-secrets/src/secret.spec.ts
- packages/lambda-secrets/src/secrets.ts
- pnpm-lock.yaml
The lambda secret layer can have hang up issues, so to combat this we are adding some retry logic. 
Seperately node-fetch seems to be a bit hit or miss with http requests. In testing it seems native fetch works better for this use case.
> fix(lambda-layer): native fetch & retries

- servers/v3-proxy-api/src/routes/validations/FetchSchema.ts
Android does not fetch annotations by default on initial login, but should so users get their highlights.
https://mozilla-hub.atlassian.net/browse/POCKET-9924
> fix(fetch): default annotations to on for fetch

- infrastructure/list-api/src/main.ts
- pnpm-lock.yaml
- servers/list-api/package.json
- servers/list-api/schema.graphql
- servers/list-api/src/resolvers/index.ts
- servers/list-api/src/test/graphql/queries/readerSlug.integration.ts
- servers/parser-graphql-wrapper/schema.graphql
- servers/parser-graphql-wrapper/src/config/index.ts
- servers/parser-graphql-wrapper/src/dataLoaders/itemLoader.ts
- servers/parser-graphql-wrapper/src/model.ts
- servers/parser-graphql-wrapper/src/readerView/index.ts
- servers/parser-graphql-wrapper/src/readerView/readerViewResult.integration.ts
- servers/parser-graphql-wrapper/src/resolvers.ts
Implementation for contract described [here](https://mozilla-hub.atlassian.net/wiki/spaces/PE/pages/616726765/Sharing+Reader+View)
list-api: resolve SavedItem on readerSlug query if it exists
parser-graphql-wrapper: resolve interstitial data (fallback page) with item summary if it exists, or basically a 404 message.
[POCKET-9866]
[POCKET-9866]: https://mozilla-hub.atlassian.net/browse/POCKET-9866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(readerSlug): add reader interstitial data

- servers/list-api/src/resolvers/savedItem.ts
parser-graphql wrapper prefers itemId, which does
not always return the itemId which was saved in a
user's list (the originating data source) due to
vagaries of resolvedId/itemId/normalUrl lookup.
> fix(item): resolve item by givenUrl from list-api

- .circleci/common.yml
It looks like we are using 1.1 TB of egress network costs due to caching within our hosted runner. This removes all caching within the CircleCI hosted runner for now to save on egress network costs which make up more then half the circleci bill.
This also disables docker layer caching which is also way above our maximum for now as well.
> chore(circleci): optimizing costs

- servers/annotations-api/src/test/mutation/highlights-batchwrite.integration.ts
- servers/annotations-api/src/test/mutation/highlights-create.integration.ts
- servers/annotations-api/src/test/mutation/highlights-delete.integration.ts
- servers/annotations-api/src/test/mutation/highlights-update-deprecated.integration.ts
- servers/annotations-api/src/test/mutation/highlights-update.integration.ts
- servers/list-api/src/test/graphql/mutations/clearTags.integration.ts
- servers/list-api/src/test/graphql/mutations/replaceTags.integration.ts
- servers/list-api/src/test/graphql/mutations/savedItemById/createSavedItemTagsMutation.integration.ts
- servers/list-api/src/test/graphql/mutations/savedItemById/reAdd.integration.ts
- servers/list-api/src/test/graphql/mutations/savedItemById/savedItemsMutationService-delete.integration.ts
- servers/list-api/src/test/graphql/mutations/savedItemById/savedItemsMutationService-updates.integration.ts
- servers/list-api/src/test/graphql/mutations/savedItemById/savedItemsMutationService-upsert.integration.ts
- servers/list-api/src/test/graphql/mutations/tagsById/tagsMutationService-replaceSavedItemTags.integration.ts
- servers/list-api/src/test/graphql/mutations/tagsById/tagsMutationService-update.integration.ts
- servers/list-api/src/test/graphql/mutations/tagsById/tagsMutationService-updateSavedItemTags.integration.ts
- servers/list-api/src/test/graphql/mutations/tagsByName/deleteTagByName.integration.ts
- servers/list-api/src/test/graphql/mutations/tagsByName/removeTagsByName.integration.ts
- servers/list-api/src/test/graphql/mutations/tagsByName/renameTagByName.integration.ts
- servers/user-api/src/events/eventBus/eventBusHandler.spec.ts
- servers/user-list-search/src/freeSearch.integration.ts
- servers/user-list-search/src/freeSearchByOffset.integration.ts
- servers/v3-proxy-api/src/routes/v3Send.integration.ts
When I moved the list api and other services, I moved them and replaced sinon with pure jest. There was some weird behavior with the new timers behavior in Jest that I could not fully sort out at the time that caused us to have to set `advanceTimers` to `true`.  This had the side effect of causing our tests that check dates to be a bit flakey because the time could increment in the amount of time it took to run the test instead of being 
Upon looking into the behavior `advanceTimers` was needed because the new timer behavior fakes async tick functions that we don't want it to. See https://github.com/nock/nock/issues/2200#issuecomment-1280957462
By telling jest to not fake the async node functions, the clock stays frozen and the rest of the code can execute.
> fix(tests): making the tests not change the time

- servers/parser-graphql-wrapper/src/preview/preview.ts
- servers/parser-graphql-wrapper/src/resolvers.ts
No tests???? I know, I know... but it is such an absolutely huge PITA to make the mocks for this data, and I'm basically adding one additional line that uses an already-tested function... we're discussing making this repo more developer friendly :) 
And I'd mock the federated entity for a graph query test, so I don't see much benefit for doing all the work it would take to just test the entity federation on PocketShare.
[POCKET-9870]
[POCKET-9870]: https://mozilla-hub.atlassian.net/browse/POCKET-9870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(shares): federate PocketShare.preview field

- servers/v3-proxy-api/src/graph/get/toGraphQL.spec.ts
- servers/v3-proxy-api/src/graph/get/toGraphQL.ts
- servers/v3-proxy-api/src/routes/v3Fetch.ts
- servers/v3-proxy-api/src/routes/validations/FetchSchema.ts
- servers/v3-proxy-api/src/routes/validations/GetSchema.ts
Optional field, if true returns only Saves which
have annotations. Used for android fetching
Archive, which do not cache annotations on device.
Is ignored if a search term is passed.
[POCKET-9929]
[POCKET-9929]: https://mozilla-hub.atlassian.net/browse/POCKET-9929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(v3proxy): add hasAnnotations option

- servers/shares-api/schema.graphql
- servers/shares-api/src/__generated__/types.ts
- servers/shares-api/src/models/PocketShare.ts
- servers/shares-api/src/test/Max300CharString.integration.ts
- servers/shares-api/src/test/createShareLink.integration.ts
- servers/shares-api/src/test/queries.ts
Previously returned only the shareUrl. Return the
entire entity for future flexibility on server-generated data.
Helps mobile clients with their internal storage.
[POCKET-9984]
[POCKET-9984]: https://mozilla-hub.atlassian.net/browse/POCKET-9984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(shares): return entire entity for createShareLink

- servers/parser-graphql-wrapper/src/__generated__/resolvers-types.ts
- servers/parser-graphql-wrapper/src/apollo/resolvers.ts
- servers/parser-graphql-wrapper/src/readerView/readerSlug.spec.ts
- servers/parser-graphql-wrapper/src/readerView/readersSlug.ts
- servers/parser-graphql-wrapper/src/test/queries/readerUrl.integration.ts
- servers/v3-proxy-api/src/generated/graphql/types.ts
When a `getpocket.com/read/[slug]` is requested from the parser, we should attempt to resolve it to the original item object. This will ensure that iOS, Android and Web get the right metadata in the saves view and all other item queries.
https://mozilla-hub.atlassian.net/browse/POCKET-10000
> fix(reader): adding in a reader url resolver

- servers/v3-proxy-api/src/routes/v3Get.integration.ts
- servers/v3-proxy-api/src/routes/validations/GetSchema.ts
Accept 'relevance' sort even if search query is
omitted or malformed, but convert it to 'newest'.
For Android which can send empty search queries
to request recent search values.
> feat(v3proxy): conditionally set sort defaults depending on search

- infrastructure/shares-api/src/main.ts
- pnpm-lock.yaml
- servers/shares-api/schema.graphql
- servers/shares-api/src/__generated__/types.ts
- servers/shares-api/src/apollo/context.ts
- servers/shares-api/src/apollo/resolvers.ts
- servers/shares-api/src/config/index.ts
- servers/shares-api/src/datasources/shares.ts
- servers/shares-api/src/models/PocketShare.ts
- servers/shares-api/src/models/ShareNotFoundModel.ts
- servers/shares-api/src/models/UserContext.ts
- servers/shares-api/src/test/Max300CharString.integration.ts
- servers/shares-api/src/test/addShareContext.integration.ts
- servers/shares-api/src/test/createShareLink.integration.ts
- servers/shares-api/src/test/operations.ts
- servers/shares-api/src/test/shareSlug.integration.ts
To speed up the experience of creating links;
create the link on one view with a mutation, then optionally
use this mutation to attach context.
This is intended as a step done immediately after sharing the link, not coming back to it way later. This is why we can use the guid. It also lets us enable logged-out users to share links and have the same behavior, if we want to in the future.
** Changes **
* Created salts for userId (unused, but maybe in the future) and guid; uploaded to aws prod and dev accounts
* Save hashed + salted userId + guid (if available from JWT) when creating shares -- this future-proofs if we want to look up by the hashed userid in the future; note this is a one-way lookup, not an encryption/masking
* Add mutation to attach context to a link - checks hashed guid for …
> feat(shares): edit share context after creation

- servers/v3-proxy-api/src/generated/graphql/types.ts
- servers/v3-proxy-api/src/graph/graphQLClient.ts
Handle partial error/data response, since we still want the rest of the data even if recentSearch returns null + Forbidden error (i.e. if the requester is not logged into a premium account). Supports Android pattern for retrieving recent search history.
[POCKET-10034]
This was tested manually by making real calls to the graph using a premium and non-premium account. I'm trying to figure out if it's possible to test this another way, but I can't mock the `GraphQLClient.request` method anymore because it will not invoke the middleware... Alternative is standing up a local graph server that mirrors prod or making canary requests to the real graph...
[POCKET-10034]: https://mozilla-hub.atlassian.net/browse/POCKET-10034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
> feat(v3proxy:errors): skip Forbidden errors orginating from recentSearch

- servers/annotations-api/src/dataservices/highlights.ts
- servers/annotations-api/src/test/query/highlights-fixtures.ts
- servers/annotations-api/src/test/query/highlights.integration.ts
Currently there are some 'v1' annotations which have null patches in the database. These annotations were available to a smaller cohort of beta android users in 2017 and were superseded by the current 'v2' annotations in late 2017. Rarely these annotations are being requested (mostly by our internal test accounts) and result in a server error when GraphQL rejects the null value due to 'patch' not being nullable in the schema.
This converts these rare patches to empty strings rather than introducing a breaking change. Confirmed with iOS and web clients that the 'v1' patches are handled differently/ that empty patches will simply be discarded. So there should be no change in visual behavior other than reducing errors.
[POCKET-1033]
> fix(annotations): convert null patch to empty string

- servers/parser-graphql-wrapper/src/models/pocketMetadataModels/OEmbedModel.ts
I noticed that the image urls returned from the TikTok oembed endpoint only last for 2 days. 
If this is a theme, we will need to build TTL into the model, or cache the tiktok image urls 🤔
> fix(oembed): expire oembed data after 2 days

- servers/parser-graphql-wrapper/schema.graphql
Adding some additional documentation for nested fields, and tweaking the wording of the base type documentation (remove 'shared' to disambiguate with sharing).
There was an assumption that the typical case for accessing a getpocket.com/read/ link which resolves to an item not in your saves is because someone that _did_ have it copy-pasted the read link to you, but that's not the only case. Update to reflect.
> chore: update readerSlug documentation

- servers/v3-proxy-api/src/routes/v3Send.integration.ts
- servers/v3-proxy-api/src/routes/validations/SendSchema.ts
Previously we were assuming all query params were
still encoded strings; this is not true for some
GET request patterns. This PR first attempts to
parse actions array as JSON; if it fails, then
try decoding the string (assuming uri-encoded)
before reparsing as JSON.
In many cases it was fine to decode the already-
decoded string again, because the actions array
typically did not include special characters. But
since it's user input it's possible to say, make a tag with a percent sign. That was causing the whole thing to fail because it wasn't valid url encoding.
[POCKET-10048]
[POCKET-10048]: https://mozilla-hub.atlassian.net/browse/POCKET-10048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(v3proxy:send): fallback parsing for actions array

- servers/v3-proxy-api/src/routes/v3Send.integration.ts
- servers/v3-proxy-api/src/routes/validations/SendActionValidators.ts
Changes the replace_tags action to clear_tags action if replacement value is empty
[POCKET-10098]
[POCKET-10098]: https://mozilla-hub.atlassian.net/browse/POCKET-10098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(v3proxy:tags): clear tags if replacement is empty

- servers/shares-api/src/events/EventBus.ts
Was missing the key that snowplow was looking
for, and instead just had the object as the
payload.
> fix(shares:events): fix share event detail schema

- .docker/aws-resources/elasticsearch/esindex_corpus_de.json
- .docker/aws-resources/elasticsearch/esindex_corpus_en.json
- .docker/aws-resources/elasticsearch/esindex_corpus_es.json
- .docker/aws-resources/elasticsearch/esindex_corpus_fr.json
- .docker/aws-resources/elasticsearch/esindex_corpus_it.json
- .docker/aws-resources/elasticsearch/esindex_list.json
- .docker/aws-resources/user-list-search.sh
- infrastructure/user-list-search/apollo_ecs.tf
- infrastructure/user-list-search/locals.tf
- servers/user-list-search/src/config/index.ts
- servers/user-list-search/src/datasource/elasticsearch/advancedSearch.integration.ts
- servers/user-list-search/src/datasource/elasticsearch/elasticsearchBulk.integration.ts
- servers/user-list-search/src/datasource/elasticsearch/elasticsearchBulk.ts
- servers/user-list-search/src/datasource/elasticsearch/elasticsearchSearch.integration.ts
- servers/user-list-search/src/datasource/elasticsearch/elasticsearchSearch.ts
- servers/user-list-search/src/elasticsearch.integration.ts
- servers/user-list-search/src/elasticsearch.ts
- servers/user-list-search/src/premiumSearch.integration.ts
- servers/user-list-search/src/premiumSearchByOffset.integration.ts
- servers/user-list-search/src/server/routes/itemDelete.integration.ts
- servers/user-list-search/src/server/routes/itemUpdate.integration.ts
Set up local infrastructure and environment variables for corpus search indices. These indices are language-specific. 
**Note that this doesn't actually create the indices on the prod/dev clusters**, but it does locally. I'm not sure how we want to capture this. In the `bin` folder? It's kind of like a schema migration.
Related changes:
* reduce the shards in the local list index
Related PR:
* enrich event bridge events with additional data: https://github.com/Pocket/content-monorepo/pull/165
[POCKET-10121]
[POCKET-10121]: https://mozilla-hub.atlassian.net/browse/POCKET-10121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(search:corpus): add indices for language-specific corpora

- .docker/aws-resources/elasticsearch/esindex_corpus_de.json
- .docker/aws-resources/elasticsearch/esindex_corpus_en.json
- .docker/aws-resources/elasticsearch/esindex_corpus_es.json
- .docker/aws-resources/elasticsearch/esindex_corpus_fr.json
- .docker/aws-resources/elasticsearch/esindex_corpus_it.json
- lambdas/user-list-search-corpus-indexing/src/createDoc.ts
The service now emits events for draft collections, so we want to ensure we can differentiate between
published and draft collections when we return results.
Future enhancements might delete or discard this data, but since it's possible to transition from Published to Draft and there just isn't much data, it's not
expensive to just keep it around for now as we decide on exactly how we want to model.
Note that this field being passed was already covered in tests, it just wasn't included on the elasticsearch request. So it is covered in integration tests without any changes.
I have already updated dev and prod indices to accept this field.
> fix(search:corpus): add status to corpus indices

- lambdas/annotations-api-events/src/index.spec.ts
- lambdas/annotations-api-events/src/index.ts
Fix a sentry bug that started popping up now that sentry is on the lambdas.
We should never throw on event handlers missing, unless the infrastructure will only ever send the appropriate handled events.
POCKET-10181
> fix(annotations-api): making no handler implemented a log instead of an error

- infrastructure/user-list-search/backfill_item_update_consumer.tf
- infrastructure/user-list-search/backfill_user_list_import_consumer.tf
- infrastructure/user-list-search/corpus_events_consumer.tf
- infrastructure/user-list-search/event_handler_consumer.tf
- infrastructure/user-list-search/item_delete_consumer.tf
- infrastructure/user-list-search/item_update_consumer.tf
- infrastructure/user-list-search/user_list_import_consumer.tf
Temporarily disable event source mappings for the user-list-search lambdas. Processing these messages results in write activity on the elasticsearch (ES) cluster, e.g. index/update/delete. Temporarily disabling these enables us to perform an ES migration without potentially losing data from events that were unable to be processed. When re-enabled, the messages will be processed as usual.
Translation from kinesis stream to SQS messages is not disabled, since this lambda does not directly result in making requests to the ES cluster (requires the lambdas which are disabled).
**Testing**
Deployed this change to dev and confirmed that the triggers were removed from the lambda.
Note that when we revert this change after the ES migration completes, we will also have to update the elasticsearch …
> chore(search): disable search SQS message processing for ES migration

- .docker/aws-resources/elasticsearch/esindex_corpus_de.json
- .docker/aws-resources/elasticsearch/esindex_corpus_en.json
- .docker/aws-resources/elasticsearch/esindex_corpus_es.json
- .docker/aws-resources/elasticsearch/esindex_corpus_fr.json
- .docker/aws-resources/elasticsearch/esindex_corpus_it.json
- lambdas/user-list-search-corpus-indexing/src/config.ts
- lambdas/user-list-search-corpus-indexing/src/createDoc.ts
- lambdas/user-list-search-corpus-indexing/src/types.ts
New fields included on events, which indicate
the source of the curation (e.g. ML prospect
or manual curation add), and the grade of
the content (A/B/C) as a numeric ranking.
Relates to https://github.com/Pocket/content-monorepo/pull/178
TODO:
> feat(search:corpus): support source and grade fields

- .circleci/user-list-search.yml
- .docker/aws-resources/elasticsearch/esindex_corpus_de.json
- .docker/aws-resources/elasticsearch/esindex_corpus_en.json
- .docker/aws-resources/elasticsearch/esindex_corpus_es.json
- .docker/aws-resources/elasticsearch/esindex_corpus_fr.json
- .docker/aws-resources/elasticsearch/esindex_corpus_it.json
- infrastructure/user-list-search/corpus_events_hydration_consumer.tf
- infrastructure/user-list-search/corpus_events_hydration_consumer_codedeploy.tf
- infrastructure/user-list-search/locals.tf
- infrastructure/user-list-search/main.tf
- infrastructure/user-list-search/sqs.tf
- infrastructure/user-list-search/sqs_sns_topic_subscription.tf
- lambdas/user-list-search-corpus-parser-hydration/eslint.config.mjs
- lambdas/user-list-search-corpus-parser-hydration/jest.config.js
- lambdas/user-list-search-corpus-parser-hydration/package.json
- lambdas/user-list-search-corpus-parser-hydration/src/bulkIndex.ts
- lambdas/user-list-search-corpus-parser-hydration/src/config.ts
- lambdas/user-list-search-corpus-parser-hydration/src/index.integration.ts
- lambdas/user-list-search-corpus-parser-hydration/src/index.spec.ts
- lambdas/user-list-search-corpus-parser-hydration/src/index.ts
- lambdas/user-list-search-corpus-parser-hydration/src/parserRequest.ts
- lambdas/user-list-search-corpus-parser-hydration/src/types.ts
- lambdas/user-list-search-corpus-parser-hydration/tsconfig.json
- pnpm-lock.yaml
Infrastructure and implementation for a new lambda + sqs queue. Uses the SNS/SQS fan-out pattern to fan out corpus-related messages to this new SQS queue, which makes a request to the parser and then updates the document with a number of parser-supplied fields.
The processing on this queue is delayed by 5 minutes to allow for the initial indexing action to be processed.
Allows us to connect corpus items to Pocket Item entity, and for additional search capabilities with full text extraction, content type filters, etc.
Deployed to dev and tested with both collection and corpus events. 
[POCKET-10198]
TODO:
[POCKET-10198]: https://mozilla-hub.atlassian.net/browse/POCKET-10198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(search:corpus): lambda to hydrate corpus with parser data

- .docker/mysql-8-resources/schema/01a-mono-db-readitla_ril-tmp-schema.sql
- servers/list-api/src/dataService/listPaginationService.ts
- servers/list-api/src/test/graphql/queries/savedItems.integration.ts
Update schema of local tables related to list
to use bigint, and the temp table used to paginate.
[POCKET-9326]
[POCKET-9326]: https://mozilla-hub.atlassian.net/browse/POCKET-9326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(list): int->bigint temp table migration

- servers/user-list-search/src/server/routes/userListImport.integration.ts
The tests are intended to check whether all the items in
a user's list are processed in chunks of up to a certain
size. They have been updated to reflect this and not
flake due to ordering issues.
> fix(search:test): remove ordered assertions from test

- servers/v3-proxy-api/src/routes/ActionsRouter.ts
- servers/v3-proxy-api/src/routes/v3Send.integration.ts
Fixes a typo which was causing the default error data to be undefined.
Added test coverage for accessing the default error data.
[POCKET-10240]
[POCKET-10240]: https://mozilla-hub.atlassian.net/browse/POCKET-10240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(v3proxy): fix typo in default error and add test coverage

- servers/v3-proxy-api/src/routes/v3Get.integration.ts
- servers/v3-proxy-api/src/routes/validations/FetchSchema.ts
- servers/v3-proxy-api/src/routes/validations/GetSchema.ts
- servers/v3-proxy-api/src/routes/validations/shared.spec.ts
- servers/v3-proxy-api/src/routes/validations/shared.ts
Infers seconds vs. milliseconds with constraints (do not need
to support timestamps prior to 2001 or thousands of years from
now)
[POCKET-10239]
[POCKET-10239]: https://mozilla-hub.atlassian.net/browse/POCKET-10239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(v3proxy): convert epoch timestamps in request to seconds

- packages/sentry/src/initSentry.ts
It seems that a sentry update disabled the integrations we want by default if you don't pass in a trace sample rate option, even if its 0.
https://github.com/getsentry/sentry-javascript/blob/develop/packages/node/src/sdk/index.ts#L82-L84
> fix(sentry): ensuring integrations are added to sentry

- .docker/aws-resources/user-list-search.sh
- lambdas/user-list-search-corpus-indexing/src/index.integration.ts
- servers/user-list-search/src/datasource/elasticsearch/advancedSearch.integration.ts
- servers/user-list-search/src/datasource/elasticsearch/elasticsearchBulk.integration.ts
- servers/user-list-search/src/datasource/elasticsearch/elasticsearchBulk.ts
- servers/user-list-search/src/datasource/elasticsearch/elasticsearchSearch.integration.ts
- servers/user-list-search/src/datasource/elasticsearch/elasticsearchSearch.ts
- servers/user-list-search/src/datasource/elasticsearch/searchQueryBuilder.spec.ts
- servers/user-list-search/src/datasource/elasticsearch/searchQueryBuilder.ts
- servers/user-list-search/src/elasticsearch.integration.ts
- servers/user-list-search/src/premiumSearchByOffset.integration.ts
- servers/user-list-search/src/server/routes/itemDelete.integration.ts
- servers/user-list-search/src/server/routes/itemUpdate.integration.ts
[x] API tested in dev (could not test lambda integration because of calls to mysql db looking for premium user status)
Update localstack search cluster to be opensearch,
not elasticsearch. Note that the latest version we
could get locally is 2.11 but we are at 2.13 on AWS.
Remove 'type' (e.g. /_doc) from bulk query
endpoint.
Update score sort to explicitly include ordering,
rather than just passing the '_score' string.
Add a tiebreaker sort on 'item_id' for when _score
is identical among results.
Remove some unnecessary comparisons in test assertions
to clean up the code and streamline what we're checking.
[POCKET-10244]
[POCKET-10244]: https://mozilla-hub.atlassian.net/browse/POCKET-10244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(search): update queries for os_2.13 upgrade

- infrastructure/user-list-search/ecs.tf
- infrastructure/user-list-search/main.tf
- servers/user-list-search/src/config/index.ts
Articles may be hidden from end-user clients due
to publisher request to default to original view.
We do not currently use the Parser service, but
once we do this will enable us to claim as a
privileged service to pull article content for
full text search indexing.
[POCKET-10247]
[POCKET-10247]: https://mozilla-hub.atlassian.net/browse/POCKET-10247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(search/article): add secret ID to access article view

- servers/v3-proxy-api/src/routes/validations/SendActionValidators.ts
- servers/v3-proxy-api/src/routes/validations/sendActionValidators.spec.ts
Previously it was assumed only strings were
sent, but we can see that numeric IDs are sent
occasionally (which was causing an error when
calling string methods).
[POCKET-10281]
[POCKET-10281]: https://mozilla-hub.atlassian.net/browse/POCKET-10281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(v3proxy): accept numeric item_ids

- lambdas/user-list-search-corpus-indexing/src/index.integration.ts
- lambdas/user-list-search-corpus-indexing/src/types.ts
- lambdas/user-list-search-corpus-parser-hydration/src/index.integration.ts
- lambdas/user-list-search-corpus-parser-hydration/src/types.ts
Was causing events to be filtered out that
should not have been, resulting in empty body
in requests to elasticsearch.
[POCKET-10281]
[POCKET-10281]: https://mozilla-hub.atlassian.net/browse/POCKET-10281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(corpus:search): fix typo in event name

- lambdas/user-list-search-indexing/src/helper.ts
- servers/list-api/src/externalCaller/parserCaller.spec.ts
- servers/list-api/src/externalCaller/parserCaller.ts
Remove url from error message for better Sentry
grouping.
Add breadcrumbs for tracking
Only parse response as JSON if OK -- otherwise
fetch body text (put into breadcrumbs) and throw
parsing error.
> chore(list): observability improvements

- infrastructure/user-list-search/backfill_item_update_consumer.tf
- infrastructure/user-list-search/backfill_user_list_import_consumer.tf
- infrastructure/user-list-search/corpus_events_consumer.tf
- infrastructure/user-list-search/corpus_events_hydration_consumer.tf
- infrastructure/user-list-search/event_handler_consumer.tf
- infrastructure/user-list-search/item_delete_consumer.tf
- infrastructure/user-list-search/item_update_consumer.tf
- infrastructure/user-list-search/locals.tf
- infrastructure/user-list-search/user_list_import_consumer.tf
We don't want runaway lambdas, especially if
they're all making requests to one service.
[POCKET-10252]
[POCKET-10252]: https://mozilla-hub.atlassian.net/browse/POCKET-10252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(search): add max concurrency limits on lambdas

- infrastructure/user-list-search/locals.tf
- lambdas/user-list-search-corpus-parser-hydration/src/config.ts
- lambdas/user-list-search-corpus-parser-hydration/src/parserRequest.ts
This is not served to the end-user and purely aids in
discovery of content (which would have the positive
end-result of driving more traffic to the publisher).
[POCKET-10285]
[POCKET-10285]: https://mozilla-hub.atlassian.net/browse/POCKET-10285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(corpus:content): enable privileged content extraction for hydrator

- lambdas/user-list-search-corpus-indexing/src/createDoc.ts
- lambdas/user-list-search-corpus-indexing/src/utils.spec.ts
- lambdas/user-list-search-corpus-indexing/src/utils.ts
- lambdas/user-list-search-corpus-parser-hydration/src/index.integration.ts
- lambdas/user-list-search-corpus-parser-hydration/src/index.ts
- lambdas/user-list-search-corpus-parser-hydration/src/utils.spec.ts
- lambdas/user-list-search-corpus-parser-hydration/src/utils.ts
Makes requests to the parser for collections to generate
the records and identifiers used to federate them as Pocket Items.
Add some additional seeding to the test to reflect this.
Standardize casing for status (historically it's uppercase but
is now lowercase -- when we reprocess the dataset, standardize
on lowercase).
Create urls for collections rather than just putting the slugs
there; sometimes the slugs in historical data are full URLs, and
sometimes they are just slugs. Parse conditionally so when we
reprocess data they are all standardized.
[POCKET-10301]
[POCKET-10301]: https://mozilla-hub.atlassian.net/browse/POCKET-10301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(corpus:index): fix collection urls and standardize casing

- .docker/aws-resources/elasticsearch/esindex_corpus_de.json
- .docker/aws-resources/elasticsearch/esindex_corpus_en.json
- .docker/aws-resources/elasticsearch/esindex_corpus_es.json
- .docker/aws-resources/elasticsearch/esindex_corpus_fr.json
- .docker/aws-resources/elasticsearch/esindex_corpus_it.json
- lambdas/user-list-search-corpus-indexing/src/createDoc.ts
- lambdas/user-list-search-corpus-indexing/src/index.integration.ts
- lambdas/user-list-search-corpus-indexing/src/types.ts
Want to use the ApprovedItem ID for deterministic
sort response. To do it efficiently we should not
use the _id field but should denormalize the data
and copy it into a doc_values field.
**TODO**
> chore(corpus:search): denormalize ID for sorting

- infrastructure/account-data-deleter/src/dataDeleterApp.ts
Remove noisy alarm that consistently does not have enough data.
> fix(account-data-deleter): removing alarm thats noisy

- servers/v3-proxy-api/src/graph/get/toGraphQL.ts
- servers/v3-proxy-api/src/routes/v3Get.integration.ts
- servers/v3-proxy-api/src/routes/validations/GetSchema.ts
Enables passing contentType=all to v3/get
[POCKET-10339]
[POCKET-10339]: https://mozilla-hub.atlassian.net/browse/POCKET-10339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(v3proxy:get): add contentType=all to get schema

- servers/list-api/src/resolvers/mutation.ts
- servers/list-api/src/resolvers/utils.spec.ts
- servers/list-api/src/resolvers/utils.ts
- servers/list-api/src/test/graphql/mutations/savedItemById/savedItemsMutationService-upsert.integration.ts
Urls like google.com are not adding to a users list because they have no url scheme.
This will attempt to add http: as a scheme to urls like this that come through.
[POCKET-10341](https://mozilla-hub.atlassian.net/browse/POCKET-10341)
[POCKET-10341]: https://mozilla-hub.atlassian.net/browse/POCKET-10341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(scheme): adding in a url scheme if one does not exist

- infrastructure/list-api/src/main.ts
- infrastructure/parser-graphql-wrapper/src/main.ts
- infrastructure/v3-proxy-api/src/main.ts
#Goal
Looking at the AWS graphs we are doing some up and down scaling and getting lots of 502 gateway timeouts. This attempts to rectify this with some more horsepower.
I chose values based on doubling what the services averagely sit at.
> fix(scale): bump up the scaling of our main services to increase stability

- servers/user-list-search/src/corpus/keywordSearch.integration.ts
- servers/user-list-search/src/resolvers.ts
- servers/user-list-search/src/server/context.ts
For native Pocket applications only.
Adds assertion that a user is logged in to
every other mutation and User field resolver.
This is an alternative to the router-based auth
directives we were trying to use, because of a
bug which causes the entire query to be rejected
if the unauthorized component references a variable.
https://github.com/apollographql/router/issues/5648
Since we probably will migrate to router-enforced auth once this bug is fixed, this less elegant method requires the least refactoring (vs. using the more complicated auth models in other subgraphs)
[POCKET-10286]
[POCKET-10286]: https://mozilla-hub.atlassian.net/browse/POCKET-10286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(search:auth): enable logged-out corpus search

- servers/v3-proxy-api/src/middleware/errorHandlers.ts
- servers/v3-proxy-api/src/server.ts
Bump request size limit 6x
Add body and query params (except access token) to error tracking in sentry for debugging purposes
[POCKET-10338]
[POCKET-10338]: https://mozilla-hub.atlassian.net/browse/POCKET-10338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(v3proxy): bump request size limit and add logging

- servers/v3-proxy-api/src/server.ts
To accomodate catchups on old Pocket clients which also send legacy analytics events
> fix(v3proxy): bump request size limit

- servers/v3-proxy-api/src/graph/get/toRest.ts
- servers/v3-proxy-api/src/middleware/errorHandlers.ts
- servers/v3-proxy-api/src/routes/ActionsRouter.ts
- servers/v3-proxy-api/src/routes/v3Get.integration.ts
- servers/v3-proxy-api/src/routes/v3Send.integration.ts
- servers/v3-proxy-api/src/routes/validations/GetSchema.ts
- servers/v3-proxy-api/src/routes/validations/SendActionValidators.ts
- servers/v3-proxy-api/tsconfig.json
Handle ClientError reponses that are undefined.
Add additional debug logs to understand responses.
Do not accept 'add' by item_id only, and return
InvalidActionError instead.
[POCKET-10354]
I enabled strictNullChecks and fixed all files which interacted with v3/send. The main issue with turning it on for the full repository was the generated graphql types, which were causing unexpected/strange null issues for the compiler.
[POCKET-10354]: https://mozilla-hub.atlassian.net/browse/POCKET-10354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(v3proxy): handle undefined error data

- servers/parser-graphql-wrapper/src/apollo/server.ts
- servers/parser-graphql-wrapper/src/config/index.ts
Bump request size limit. Sentry is showing that we are getting 413 errors originating from the parser, for some v3proxy requests.
[POCKET-10351]
[POCKET-10351]: https://mozilla-hub.atlassian.net/browse/POCKET-10351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(parser): bump request size limit

- packages/tracing/src/tracing.ts
Seeing "Accessing resource attributes before async attributes settled" errors in v3 proxy after the package update. Implementing fixed referenced in the issue below.
https://github.com/open-telemetry/opentelemetry-js/issues/4638
[POCKET-10371]
[POCKET-10371]: https://mozilla-hub.atlassian.net/browse/POCKET-10371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(otel): fix async resource attribute access issue

- .circleci/shareable-lists-api.yml
Fix errors in Curation Admin Tools on the Shareable Lists Moderation page - an error was coming back from the graph saying `searchShareableLists` query does not exist. It turns out there was a misconfiguration in the Admin graph - while the schema was correct, the subgraph for Shareable Lists was pointing to the public URL instead of the admin URL.
Note: deployed to Dev for verification.
Previously on Dev:
```
rover subgraph list pocket-admin-api@development
Listing subgraphs for pocket-admin-api@development using credentials from the default profile.
<snip>
────────────────┼────────────────────────────┤
│ shareable-lists-api │ https://shareablelistsapi.getpocket.dev        │ 2024-02-03 09:59:30 +11:00 │
├─────────────────────┼────────────────────────────────
<snip>
```
Now on Dev:
``` …
```
> fix(shareable lists): [MC-1162] Fix Admin subgraph errors for shareable lists

- servers/v3-proxy-api/src/config/index.ts
- servers/v3-proxy-api/src/graph/graphQLClient.ts
- servers/v3-proxy-api/src/routes/ActionsRouter.ts
- servers/v3-proxy-api/src/routes/v3Add.ts
- servers/v3-proxy-api/src/routes/v3Send.integration.ts
- servers/v3-proxy-api/src/routes/v3Send.ts
- servers/v3-proxy-api/src/utils.spec.ts
- servers/v3-proxy-api/src/utils.ts
Note that I have some extension-specific code checks which I ended up not using in this PR, but they will be used in subsequent PRs (due to changing `/v3/get` response for extensions).
This is a follow up from #663, which we reverted due to reports from 3rd party API users.
I am reasonably certain that _only_ the `/v3/send` response for the `add` action is flattened, and not the response for `/v3/add` itself.
Investigation and testing:
* When #663 was merged, I received bug reports from 3rd party API users about the unnesting
* Our [developer documentation](https://getpocket.com/developer/docs/v3/add) indicates that `/v3/add` response data is nested under the `item` key
* Our native apps and extensions return nested `/v3/add` results (tested with ios and chrome extension consumer keys)
* …
> fix(v3proxy:extensions): flatten /send response for extensions

- .github/actions/ecs-codedeploy/action.yml
- .github/workflows/status-checks.yml
We should use a polling job instead of a trigger. The trigger was nice, but it created a bunch of notifications.
> fix(status-checks): switching to a polling job for status checks

- infrastructure/image-api/src/main.ts
Image API is rarely used at this time and because of that, when it does get used we get an alarm message that it is going into an ok state.
Instead for now, lets turn it off until it is used more.
> fix(image): removing alarm for image api

- servers/parser-graphql-wrapper/src/models/PocketMetadataModel.ts
Titles can be empty strings, instead of showing those we should show the url.
> fix(title): deriving title to url if blank

- pnpm-lock.yaml
- servers/user-list-search/package.json
types/graphql is deprecated since graphql now provides its types.
> chore(deps): removing types-graphql

- lambdas/user-list-search-corpus-parser-hydration/src/bulkIndex.ts
- lambdas/user-list-search-corpus-parser-hydration/src/index.ts
- lambdas/user-list-search-corpus-parser-hydration/src/parserRequest.ts
Data key is deleted in the logger, which is why
the error logging was not useful.
> fix(logging): do not use data key

- servers/parser-graphql-wrapper/schema.graphql
- servers/parser-graphql-wrapper/src/__generated__/resolvers-types.ts
- servers/parser-graphql-wrapper/src/apollo/resolvers.ts
- servers/parser-graphql-wrapper/src/models/PocketMetadataModel.ts
the corpus search node preview object did not have metadata fields from other native entities. This updates the reference resolver to pull in the federated data.
I do not currently have a way to test federated requests, but I was able to test this locally connecting to the graph. Note that source correctly identifies corpus or syndication
> fix(preview): updating corpus search node preview object

- servers/parser-graphql-wrapper/schema-admin.graphql
- servers/parser-graphql-wrapper/schema.graphql
- servers/parser-graphql-wrapper/src/__generated__/resolvers-types.ts
- servers/parser-graphql-wrapper/src/apollo/resolvers.ts
Consolidate on Item resolver instead. The CorpusSearchNode preview was throwing nulls in prod.
[POCKET-10601]
[POCKET-10601]: https://mozilla-hub.atlassian.net/browse/POCKET-10601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove preview from CorpusSearchNode

- lambdas/user-list-search-corpus-parser-hydration/src/index.ts
- lambdas/user-list-search-corpus-parser-hydration/src/types.ts
With the exception of collections which might not have excerpts.
This is because the existence of an excerpt on a Corpus item is a good proxy indicator of quality/review. Items without excerpts tend to have poor metadata (e.g. a url for a title).
[POCKET-10583]
[POCKET-10583]: https://mozilla-hub.atlassian.net/browse/POCKET-10583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(corpus search): do not index embeddings for articles without excerpts

- servers/list-api/src/dataService/usersMetaService.ts
Since we are on mysql 8 we can use upsert (replace) now. Attempt to fix: https://pocket.sentry.io/issues/5838975766/?project=5761820&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0
https://github.com/knex/knex/pull/5743
> fix(onConflict): switching to upsert

- infrastructure/pocket-event-bridge/src/event-rules/corpus-events/eventConfig.ts
- infrastructure/user-list-search/sqs_sns_topic_subscription.tf
- lambdas/user-list-search-corpus-indexing/src/commands/RemoveItem.ts
- lambdas/user-list-search-corpus-indexing/src/index.integration.ts
- lambdas/user-list-search-corpus-indexing/src/index.ts
- lambdas/user-list-search-corpus-indexing/src/types.ts
Delete items in search index when 'remove-approved-item' event is received.
Does not delete Curated Corpus copy of collections (is this even a valid flow?) since the collection entity should be the source of truth. Will need to connect at some point if data cleanup is required here, but we already hide collections that are not the 'published' status so it's low risk and priority.
Manual testing completed in dev starting from curation tool.
> feat(search:corpus): ingest removed corpus events

- .docker/aws-resources/elasticsearch/esindex_corpus_de.json
- .docker/aws-resources/elasticsearch/esindex_corpus_en_luc.json
- .docker/aws-resources/elasticsearch/esindex_corpus_es.json
- .docker/aws-resources/elasticsearch/esindex_corpus_fr.json
- .docker/aws-resources/elasticsearch/esindex_corpus_it.json
- lambdas/user-list-search-corpus-indexing/src/commands/ApprovedItem.ts
- lambdas/user-list-search-corpus-indexing/src/commands/ApprovedItemCollection.ts
- lambdas/user-list-search-corpus-indexing/src/index.integration.ts
isTimeSensitive is sent for Approved Items -- ingest it into the corpus now.
I have already updated the mappings for dev and prod search clusters.
[POCKET-10628]
[POCKET-10628]: https://mozilla-hub.atlassian.net/browse/POCKET-10628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(search): ingest isTimeSensitive field

- servers/list-api/src/dataLoader/tagsDataLoader.spec.ts
- servers/list-api/src/dataService/usersMetaService.ts
- servers/list-api/src/models/tag.spec.ts
- servers/list-api/src/server/apollo.ts
- servers/list-api/src/server/context.spec.ts
- servers/list-api/src/server/context.ts
- servers/list-api/src/test/graphql/mutations/savedItemById/createSavedItemTagsMutation.integration.ts
- servers/list-api/src/test/integrations/savedItemsService.integration.ts
- servers/list-api/src/test/integrations/usersMetaService.integration.ts
Users meta can be written to as a side effect of certain v3 queries (e.g. tagslist). Previously the writer was toggled on to be used for everything to avoid a permissions error, but this resulted in heavy load on the writer node once the v3-proxy fully came online, as most v3 queries also make a read request on the users meta table (due to `tagslist`). This update uses the read-only user for read queries rather than the writer or the dynamically set connection based on operation (query/mutation). Since we don't care about the return value of any changed results on this table, we do not need to worry about managing the connection to avoid issues with eventual consistency (replication delay).
> fix(list): control read/write connection in users meta

- servers/v3-proxy-api/src/routes/v3Get.integration.ts
- servers/v3-proxy-api/src/routes/v3Get.ts
Android calls /v3/get after initial login with a forced tag list option. This is what returns all a users tags to Android for local use.   When this option is passed, we should not pass a since timestamp to the tags query
https://mozilla-hub.atlassian.net/browse/POCKET-10649
> fix(tagsList): ensure we don't pass tagsSince if forced was passed

- servers/v3-proxy-api/src/routes/v3Add.integration.ts
- servers/v3-proxy-api/src/routes/validations/AddSchema.ts
- servers/v3-proxy-api/src/routes/validations/FetchSchema.ts
The access token needs to be optional so that we can allow cookie based auth on requests made to v3 that pass to getpocket.com/graphql
> fix(accessToken): make the access token optional to allow for cookie auth

- servers/v3-proxy-api/src/routes/v3Get.integration.ts
- servers/v3-proxy-api/src/routes/v3Get.ts
Allow filling from body for GET requests and from
query params for POST requests -- and potentially
both (merged response).
> fix(v3proxy): merge querystring and body params

- servers/otel-collector/otel-collector-config.yaml
According to https://www.googlecloudcommunity.com/gc/Data-Analytics/OpenTelemetry-and-GKE/m-p/674090/highlight/true#M3861  we need to increase the timeout. The default is 12s
> fix(otel): updating google cloud timeout

- packages/tracing/src/tracing.ts
- servers/v3-proxy-api/src/graph/graphQLClient.ts
We need values to ensure that we can debug issues from our traces. The instrumentation will auto remove sensitive values should they exist.
Also fixing an issue in the v3 proxy where it would not add a header for downstream requests.
> fix(graphql): ensuring we get graphql values in traces

- packages/tracing/src/tracing.ts
Add in request header to span transformation for debugging traces and ensuring data coming in.
> fix(headers): adding in request headers

- packages/tracing/src/tracing.ts
- servers/v3-proxy-api/src/middleware/sentryTagHandler.ts
Consumer keys can come in via bodies as well as queries.
Also add in a fix to swap the priorty order of Sentry and Xray trace headers, priortizing XRay. (XRay must come last because the proprogators both write data into the same context key (sample data), and the XRay one must win.)
> fix(sentry): ensure sentry tagging checks body

- servers/v3-proxy-api/src/utils.ts
The api id was not parsing into sentry. This updates to use a named capture group to specifically pull out its data. 
Note: no idea why the other one worked in tests, but not in a debugger context.
> fix(apiId): update the regex to use a named capture group

- servers/v3-proxy-api/src/generated/graphql/types.ts
- servers/v3-proxy-api/src/routes/v3Fetch.integration.ts
- servers/v3-proxy-api/src/routes/v3Get.integration.ts
- servers/v3-proxy-api/src/routes/validations/FetchSchema.ts
- servers/v3-proxy-api/src/routes/validations/GetSchema.ts
I noticed https://pocket.sentry.io/issues/5623927204/events/93e309e8c6a54ef5bc55fb0b1102beb5/?project=4504658424102912 errors are all using booleans in the post bodies. 
This adds back that support that Web Repo supported
> fix(bools): allowing true/false in a post body for v3

- infrastructure/v3-proxy-api/src/main.ts
Given that this service gets hit from IFTT and other third parties, bumping up the task sizes and task count to avoid 504 errors.
> fix(v3): bumping task sizes for v3 proxy

- servers/parser-graphql-wrapper/schema.graphql
- servers/parser-graphql-wrapper/src/__generated__/resolvers-types.ts
- servers/parser-graphql-wrapper/src/models/PocketMetadataModel.ts
Preview is meant to replace metadata fallback. Clients rely on the id to be present and valid for at least corpus items, which it was null at times for Android (item id... can be null 😮‍💨 ). 
For a corpus item the id field here should be the approved corpus item id, for everything else it should be the Item id (which can be nullable...... _future problem_ )
> fix(corpusItem): update the preview field under a corpus Item to use a corpus item id

- infrastructure/v3-proxy-api/src/main.ts
Support moving v3 proxy to be direct behind our CDN instead of web repo.
Given this proxies to Web repo this is safe. We will want to update to only allow requests via the CDN like web repo [does](https://github.com/Pocket/Web/blob/main/.aws/production/public_alb.tf#L260-L261), in the future.
https://mozilla-hub.atlassian.net/browse/POCKET-10700
> fix(v3): move the v3 proxy to be external for CDN

- servers/account-data-deleter/src/dataService/listDataExportService.spec.ts
- servers/account-data-deleter/src/dataService/listDataExportService.ts
- servers/account-data-deleter/src/dataService/s3Service.ts
Fixes a bug where if the CSV was done in one round, it would not be written to the bucket.
> fix(export): ensure csv written for small exports

- servers/v3-proxy-api/src/graph/graphQLClient.ts
Remove sending the 200 ok error into sentry so that sentry rate limits stop getting gummed up.
We will still be able to see the data within GCP logs.
> fix(errors): removing sending a 200 ok error to sentry

- servers/account-data-deleter/src/dataService/s3Service.ts
- servers/account-data-deleter/src/queueHandlers/queueHandler.ts
- servers/account-data-deleter/src/server.ts
Remove noisy healthcheck logger. 
Manually associate async background context -- See https://docs.sentry.io/platforms/javascript/guides/node/configuration/async-context/
Tested in dev, and the polling proceeded as expected. Sentry context did show additional data through the function stack, e.g.
```
2024-10-15T11:31:18.124-07:00
{
"cursor": -1,
"errorData": {
"__SENTRY_ERROR_LOCAL_VARIABLES__": [
{
"function": "",
"vars": {
"err": "<Error: getaddrinfo ENOTFOUND pocket-db-primary-0-dev-cluster.cluster-ro-c8befui6jgnr.us-east-1.rds.amazonaws.com\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)\n    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)>"
}
},
{
"function": "Connection.",
"vars": {
"param": "<Error: getaddrinfo ENOTFOUND …
```
> chore: clean logs and async Sentry isolation

- servers/v3-proxy-api/src/main.ts
Turns out our Sentry express middleware was still capturing 200 ok errors.
I was able to emulate our GraphQL router responding this way via proxyman and manually found the options that suppressed it.
Also in testing I determined that we respond with a 200 and an error body in this case.
> fix(sentry): filter out 200 ok errors

- servers/account-data-deleter/src/dataService/listDataExportService.ts
- servers/account-data-deleter/src/dataService/s3Service.ts
Forgot to update the zip method when I added the prefix helper -- this fixes that.
Also, even though the typescript transpiler didn't throw an error, at runtime serverLogger.warning was throwing an error due to not being a function...
> fix(export): export prefix and logger warn

- .github/workflows/publish.yml
some of the underlying publish commands use NPM_TOKEN, some us NODE_AUTH_TOKEN...
> fix(npm): some of the pnpm publish commands need the token as NODE_AUTH_TOKEN

- infrastructure/pocket-event-bridge/src/event-rules/utils.ts
Remove the new noise in #pkt-alerts that goes off every day since 10/11/2024.  Looking at the alarms nothing is wrong and the alarm is flapping from having '0' to missing data. Something may have changed on AWS's side.. 🤷
> fix(alarms): updating dlq alarm logic

- servers/client-api/config/router.yaml
Redploy of https://github.com/Pocket/pocket-monorepo/pull/831 without compression turned off and on.
Testing locally, it appears recs api does not support compression, (see screenshot). This retry setting does work though with compression not enabled.
> fix(router): adding in router retries for errors

- infrastructure/account-data-deleter/src/dataDeleterApp.ts
- infrastructure/account-data-deleter/src/main.ts
- servers/account-data-deleter/src/config/index.ts
- servers/account-data-deleter/src/dataService/listDataExportService.ts
- servers/account-data-deleter/src/dataService/s3Service.ts
Use an IAM User instead of the ECS execution task role for the presigned url access grant. This is so that the url does not expire prior to when we want it to (7 days). I can't fully test whether this lasts, but I have a URL that was generated which I can check over the next few days to be sure. At the very least, it shouldn't degrade the experience.
See https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html#who-presigned-url for more info.
> fix(export): use iam user for presigned url access grant

- servers/v3-proxy-api/src/main.ts
Some clients send charset UTF8 which is not a valid charset. Ignoring it per https://github.com/expressjs/body-parser/issues/50
https://pocket.sentry.io/issues/5999859912/?project=4504658424102912&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=1
> fix(sentry): ignoring unsupported media type errors

- infrastructure/account-data-deleter/src/config/index.ts
- infrastructure/account-data-deleter/src/lambda/batchDeleteLambdaResources.ts
- lambdas/account-data-deleter-events/src/handlers/accountDelete/index.spec.ts
- lambdas/account-data-deleter-events/src/handlers/accountDelete/index.ts
- servers/account-data-deleter/src/routes/queueDelete.ts
- servers/account-data-deleter/src/routes/schemas.ts
Ensure that deletes allow for a null/undefined email address since some really old users do not have associated emails
> fix(account-delete): making emails optional for deletion in account deleter

- lambdas/annotations-api-events/src/handlers/accountDelete.ts
- servers/annotations-api/src/server/routes/queueDelete.integration.ts
- servers/annotations-api/src/server/routes/queueDelete.ts
Allow annotations api to delete without email addresses or premium flags.
> fix(accountDeleter): allow annotations api to delete without email

- servers/client-api/config/router.yaml
Looking in Client API Error logs there are requests that exceed our Root field limit. Looking at the requests it looks like they are from Web Client batch mutations.
Upping the limit to support our agreed upon batch size
> fix(rootFields): upping root field limit for Web Client delete batches

- servers/client-api/config/router.yaml
- servers/client-api/config/supergraph.yaml
Add back in demand control after reversion in https://github.com/Pocket/pocket-monorepo/pull/878
When looking at logs looks like the issue was that we were creating Error Spans (traces) for every request greater then a certain cost which triggered un-needed load on the Router service.
> fix(metrics): addding back in demand control

- servers/client-api/config/router.yaml
- servers/client-api/config/supergraph.yaml
Reverts Pocket/pocket-monorepo#881
logs started filling up with `The response did not include a field corresponding to query field `
> Revert "fix(metrics): addding back in demand control"

- servers/list-api/src/externalCaller/parserCaller.spec.ts
- servers/list-api/src/externalCaller/parserCaller.ts
In some cases the parser does not return a resolvedId in its item object response. We need to check one level up for it.
> fix(resolvedId): check if the parser returned a resolved id

- servers/parser-graphql-wrapper/src/models/pocketMetadataModels/OEmbedModel.ts
- servers/parser-graphql-wrapper/src/test/queries/oembed.integration.ts
Fix [Sentry error](https://pocket.sentry.io/issues/5353210908/?project=5591912&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=4) which started when ted started adding ideas.ted.com.
Instead we not only will catch oembed errors, but will also use the packages hasProvider function.
https://mozilla-hub.atlassian.net/browse/POCKET-10744
> fix(oembed): removing error if oembed provider does not exist

- infrastructure/list-api/src/main.ts
- infrastructure/user-list-search/rds.tf
User list search was creating an outdated database deployment in our dev environment.
This updates it to serverless v2 and ensures we dont get charged for extended support
https://mozilla-hub.atlassian.net/browse/POCKET-10768
> fix(rds): ensuring dev only rds use the latest version

- servers/list-api/src/dataService/tagDataService.ts
- servers/list-api/src/resolvers/mutation.ts
- servers/list-api/src/test/graphql/mutations/batchImport.integration.ts
Fixes an issue where the transaction would be rolled back if no tags were imported, due to an empty query error
> fix(import): fix empty query if import had no tags

- servers/account-data-deleter/src/dataService/importers/ImportBase.ts
With a chunkSize of 100, we're getting messages that are too large to send in batches of 10 (e.g. 847023 bytes when 262144 is the max); batches of 2 should be safe
> fix(import): reduce batch size for sqs message limits

- servers/parser-graphql-wrapper/src/apollo/context.ts
- servers/parser-graphql-wrapper/src/models/pocketMetadataModels/OEmbedModel.ts
- servers/parser-graphql-wrapper/src/models/pocketMetadataModels/OpenGraphModel.ts
Feature flags was comparing the non encoded user id instead of our encoded one.
> fix(headers): ensuring we use the encoded id for feature flags

- package.json
Package deployment concurrency needs to be 1 because all semantic releases try and tag the repo and hit race conditions.
> fix(packages): package deployment concurrency to 1

- packages/apollo-utils/package.json
- packages/event-bridge/package.json
- packages/feature-flags-client/package.json
- packages/image-utils/package.json
- packages/jwt-utils/package.json
- packages/lambda-secrets/package.json
- packages/sentry/package.json
- packages/terraform-modules/package.json
- packages/tracing/package.json
- packages/ts-logger/package.json
- turbo.json
Semantic release was filling version numbers of our own packages with `0.0.0-development`. This is because the version in package.json only gets updated when it was being released. 
To fix the issue this will:
* Ensure that if a package is being released, any of its dependent packages run semantic release first, which handles ensuring their version is set correctly.
* Updates semantic release to set the version of the package even if its not releasing so it can be used downstream
> fix(release): ensuring that semantic release uses real version numbers

- packages/feature-flags-client/package.json
Pnpm version was returning output and it should not.
> fix(semantic-release): ensure semantic release returns nothing

- packages/apollo-utils/package.json
- packages/event-bridge/package.json
- packages/feature-flags-client/package.json
- packages/image-utils/package.json
- packages/jwt-utils/package.json
- packages/lambda-secrets/package.json
- packages/sentry/package.json
- packages/terraform-modules/package.json
- packages/tracing/package.json
- packages/ts-logger/package.json
There were issues with the /dev/null redirect so using a --silent instead
> fix(semantic-release): updating to use a silent command

- infrastructure/notes-api/src/main.ts
- packages/terraform-modules/src/base/ApplicationRDSCluster.ts
- servers/notes-api/jest.setup.js
- servers/notes-api/src/apollo/context.ts
- servers/notes-api/src/config/index.ts
- servers/notes-api/src/datasources/NoteService.ts
- servers/notes-api/src/datasources/db.ts
The notes deployment was failing because it was expecting a secret that was only created for mysql RDS instances.
This PR updates the module to create it for Postgres instances too.
It also updates the application code to have separate read/write connections, and changes all the existing connections to be read-only (since no mutations have been implemented).
> fix(notes:infra): fix note deployment and separate r/w endpoints

- .docker/aws-resources/elasticsearch/esindex_corpus_de.json
- .docker/aws-resources/elasticsearch/esindex_corpus_en_luc.json
- .docker/aws-resources/elasticsearch/esindex_corpus_es.json
- .docker/aws-resources/elasticsearch/esindex_corpus_fr.json
- .docker/aws-resources/elasticsearch/esindex_corpus_it.json
- .docker/aws-resources/elasticsearch/esindex_list.json
- docker-compose.yml
- servers/user-list-search/src/corpus/keywordSearch.integration.ts
- servers/user-list-search/src/corpus/semanticSearch.integration.ts
- servers/user-list-search/src/datasource/elasticsearch/advancedSearch.integration.ts
- servers/user-list-search/src/datasource/elasticsearch/elasticsearchBulk.integration.ts
- servers/user-list-search/src/datasource/elasticsearch/elasticsearchSearch.integration.ts
- servers/user-list-search/src/saves/elasticsearch.integration.ts
- servers/user-list-search/src/saves/premiumSearch.integration.ts
- servers/user-list-search/src/saves/premiumSearchByOffset.integration.ts
- servers/user-list-search/src/server/routes/batchDelete.ts
- servers/user-list-search/src/test/utils/corpusSeeder.ts
- servers/user-list-search/src/test/utils/searchIntegrationTestHelpers.ts
Ensure our search tests return the same results every time. 
This is fixed with a few things:
* Ensure there are no replicas
* Ensure that there is only 1 shard (for testing since shards can take minutes to update when searching)
* Ensure all documents are always deleted
* And the main thing: Setup a forcemerge which runs as an elastic search task in the background to delete old documents which were changing the relevance score, [see this for a better description of the issue](https://kulekci.medium.com/understanding-and-resolving-elasticsearch-score-changes-after-document-updates-a9f426b76e38).
> fix(search): update our flakey search tests

- pnpm-lock.yaml
- servers/notes-api/package.json
- servers/notes-api/schema.graphql
- servers/notes-api/src/__generated__/graphql.d.ts
- servers/notes-api/src/apollo/resolvers.ts
- servers/notes-api/src/models/Note.ts
- servers/notes-api/src/models/ProseMirrorDoc.spec.ts
- servers/notes-api/src/models/ProseMirrorDoc.ts
- servers/notes-api/src/test/documents/fromQuote.json
- servers/notes-api/src/test/mutations/createNoteFromQuote.integration.ts
- servers/notes-api/src/test/operations/mutations.ts
This returns a note seeded with copied content, which is wrapped in a blockquote and optionally succeeded by an attribution paragraph.
Example:
This is a copied note.
It has a couple paragraphs, maybe with some **formatting**.
---
Result:
> This is a copied note.
>
> It has a couple paragraphs, maybe with some **formatting**.
Source: <https://github.com/Pocket/pocket-monorepo/pull/986>
[POCKET-10861]
[POCKET-10861]: https://mozilla-hub.atlassian.net/browse/POCKET-10861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(note): create note from quote

- servers/notes-api/schema.graphql
- servers/notes-api/src/__generated__/graphql.d.ts
- servers/notes-api/src/apollo/resolvers.ts
- servers/notes-api/src/datasources/NoteService.ts
- servers/notes-api/src/models/Note.ts
- servers/notes-api/src/test/mutations/editNoteContent.integration.ts
- servers/notes-api/src/test/operations/mutations.ts
Update document content. Returns errors for missing note Id and malformed JSON. Not doing any ProseMirror schema validation (yet).
[POCKET-10862]
[POCKET-10862]: https://mozilla-hub.atlassian.net/browse/POCKET-10862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(notes): update document content

- servers/client-api/config/router.yaml
- servers/parser-graphql-wrapper/src/config/index.ts
Addresses timeout errors for loading pages (many taking > 5s)
> fix(parser): bump parser request timeout

- servers/v3-proxy-api/src/graph/graphQLClient.ts
- servers/v3-proxy-api/src/routes/ActionsRouter.ts
- servers/v3-proxy-api/src/routes/v3Send.integration.ts
- servers/v3-proxy-api/src/routes/validations/SendSchema.ts
We discovered that the web client was still using this endpoint for tag renames. Make access_token optional to enable cookie-based auth (analogous to v3/get).
> fix(v3proxy): allow cookie auth on v3/send

- docker-compose.yml
- servers/client-api/config/router.yaml
Tested locally to confirm the attributes were sent as expected.
Note that "graphql.errors" will be true for 'unauthorized' error, but it will not show an error reason in the 'critical' error field.
> feat(clientapi): add operation name and errors to otel instrumentation

- infrastructure/parser-graphql-wrapper/src/main.ts
The parser-graphql-wrapper is causing latency issues on graphql requests; bump minimum tasks to handle load. Scaling on cpu and memory does not correlate with increasing request latency.
> chore(parser): bump minimum tasks to 12

- lambdas/transactional-emails/src/braze.ts
- lambdas/transactional-emails/src/handlers/accountDelete.spec.ts
- lambdas/transactional-emails/src/handlers/forgotPassword.spec.ts
- lambdas/transactional-emails/src/handlers/listExportReady.spec.ts
- lambdas/transactional-emails/src/handlers/premiumPurchaseHandler.spec.ts
- lambdas/transactional-emails/src/handlers/premiumPurchaseHandler.ts
- lambdas/transactional-emails/src/handlers/userRegistrationEventHandler.spec.ts
- lambdas/transactional-emails/src/handlers/userRegistrationEventHandler.ts
- lambdas/transactional-emails/src/index.ts
Update fetch-retry to actually retry 3 times (not 2)
Add 504 Bad Gateway as a retryable status
Centralize HTTP response error logging and breadcrumb capture for Sentry
Remove unnecessary info logging statements in favor of breadcrumbs when errors are encountered.
[POCKET-10928]
[POCKET-10928]: https://mozilla-hub.atlassian.net/browse/POCKET-10928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(braze): standardize and improve observability+logging

- infrastructure/account-data-deleter/src/dataDeleterApp.ts
- lambdas/account-data-deleter-events/src/config.ts
- lambdas/account-data-deleter-events/src/handlers/accountDelete/index.spec.ts
- lambdas/account-data-deleter-events/src/handlers/accountDelete/index.ts
- lambdas/account-data-deleter-events/src/handlers/accountDelete/postRequest.ts
- pnpm-lock.yaml
- servers/account-data-deleter/package.json
- servers/account-data-deleter/src/config/index.ts
- servers/account-data-deleter/src/dataService/FxaRevoker.spec.ts
- servers/account-data-deleter/src/dataService/FxaRevoker.ts
- servers/account-data-deleter/src/routes/index.ts
- servers/account-data-deleter/src/routes/revokeFxa.ts
- servers/account-data-deleter/src/server.ts
- servers/user-api/src/config/index.ts
- servers/user-api/src/test/functional/seeds.ts
This data was deleted before on the Pocket side,
but now it will remove Pocket from integrations
so it no longer shows up on the Mozilla account page.
[POCKET-9990]
[POCKET-9990]: https://mozilla-hub.atlassian.net/browse/POCKET-9990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(deletion): revoke fxa tokens when deleting accounts

- infrastructure/user-api/src/main.ts
The auto-scaling seems to be aggressive for the load - on the dashboards we can see kind of whiplash and increase in response times. Bumping the minimum tasks from 2 to 3 to alleviate the load whiplash.
> chore(user-api): update minimum tasks from 2-3

- infrastructure/account-data-deleter/src/main.ts
- servers/account-data-deleter/src/config/index.ts
Update signed url ttl to 48 hours
Lets users request new exports more frequently.
TODO: Update the Braze email template to reflect once this change is merged in (change is drafted and just needs to be deployed)
> feat(export): limit caching to 72 hours

- servers/list-api/schema.graphql
- servers/list-api/src/featureFlags/client.ts
- servers/list-api/src/resolvers/index.ts
- servers/list-api/src/resolvers/mutation.ts
- servers/list-api/src/types/index.ts
For disabling export for maintenance -- let the queue processing finish, then we can do maintenance when we don't want new messages added to the export queue.
> feat(export): add new mutation with feature flag control

- .gitignore
- servers/account-data-deleter/src/dataService/exportStateService.spec.ts
- servers/account-data-deleter/src/dataService/exportStateService.ts
- servers/account-data-deleter/src/queueHandlers/exportAnnotationsHandler.ts
- servers/account-data-deleter/src/queueHandlers/exportListHandler.spec.ts
- servers/account-data-deleter/src/queueHandlers/exportListHandler.ts
- servers/account-data-deleter/src/queueHandlers/exportStateHandler.ts
- servers/braze-content-proxy/src/generated/graphql/types.ts
- servers/shareable-lists-api/src/background/ExportHandler.ts
- servers/v3-proxy-api/src/generated/graphql/types.ts
Adding Sentry alerts if data exports are reaching a failing threshold (i.e. above 5% for 10 minutes).
Services for export:
* list
* annotations
* shared lists
`account-data-deleter` manages the state of the overall export job
Create a Sentry Metric Alert for export failures.
Alert created: https://pocket.sentry.io/issues/alerts/rules/details/337137/
JIRA ticket:
- https://mozilla-hub.atlassian.net/browse/HNT-545
> chore(export): Add Sentry alerts for data export failures (HNT-545)

- packages/aws-utils/src/QueuePoller.ts
- servers/account-data-deleter/src/main.ts
- servers/account-data-deleter/src/server.spec.ts
- servers/account-data-deleter/src/server.ts
Prevent the export queue from backing up regularly.
AccountDataDeleter sometimes gets in a state where it fails to process items, and only it only starts up again after restarting the task. It’s not clear what the root cause is. Automatically restarting the tasks will likely address the symptoms of this issue and carry us over until exports are disabled.
> feat(account-data-deleter): restart server daily with graceful shutdown (HNT-905)

- servers/account-data-deleter/src/dataService/exportStateService.spec.ts
- servers/account-data-deleter/src/dataService/exportStateService.ts
Fix issue where URLs expire sooner than expected. Because we weren't passing through the special `presignedIamUserCredentials`, it was defaulting to the ECS task credentials, which expire every 12 hours. All S3 URLs signed with these credentials would expire at that time as well.
> fix(account-data-deleter): use presignedIamUserCredentials to sign export URLs
