Pocket/pocket-monorepo

servers/feature-flags/package.json

fix(feature flags): update start

---

pnpm-lock.yaml
servers/annotations-api/package.json
servers/annotations-api/schema.graphql
servers/annotations-api/src/dataservices/highlights.ts
servers/annotations-api/src/resolvers.ts
servers/annotations-api/src/test/mutation/highlights-batchwrite.integration.ts
servers/annotations-api/src/test/mutation/highlights-create.integration.ts
servers/annotations-api/src/test/mutation/highlights-mutations.ts
servers/annotations-api/src/types.ts
servers/annotations-api/tsconfig.json

Add batchWriteHighlights mutation - enables deleting and creating multiple highlights at once.
Done in a single transaction, so either everything failed or everything succeeded.
WILL NOT CREATE NOTES (since this feature isn't accepted formally I didn't want to waste time on it).
[POCKET-9446]
[POCKET-9446]: https://mozilla-hub.atlassian.net/browse/POCKET-9446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(annotations): add batchWriteHighlights mutation

---

.circleci/account-data-deleter.yml
.circleci/config.yml
infrastructure/account-data-deleter/src/lambda/base/sqsLambda.ts
infrastructure/account-data-deleter/src/lambda/batchDeleteLambdaResources.ts

Forgot to add a build image step for prs for account data deleter

fix(docker): adding in account data deleter docker build

---

.circleci/common.yml
.docker/mysql-8-resources/conf/local_dev.cnf
docker-compose.yml
pnpm-lock.yaml
servers/account-data-deleter/jest.config.js
servers/account-data-deleter/package.json
servers/account-data-deleter/src/routes/queueDelete.integration.ts
servers/account-data-deleter/tsconfig.json

Update tests by bringing in bits of https://github.com/Pocket/account-data-deleter/pull/467/files#diff-bc601a06b938eaedeb9ac7eb64028a0445371f981aac81ad044ad1eeac3758d7R123-R126 that I did not see!
Also locked mysql to 8.0.36 to match Auroa MySQL
https://mozilla-hub.atlassian.net/browse/POCKET-9493

fix(tests): updating tests to be non deterministic

---

servers/account-data-deleter/src/routes/queueDelete.integration.ts
servers/account-data-deleter/src/server.ts

fix(deleter): turn off the background deleter

---

.circleci/config.yml
.circleci/pocket-event-bridge.yml
infrastructure/pocket-event-bridge/src/README.md

Fix pocket-event-bridge so it doesnt save the app spec

fix(appspec): making event bridge not save appsepc

---

lambdas/fxa-webook-proxy-sqs/src/config.ts
lambdas/fxa-webook-proxy-sqs/src/jwt.ts
servers/shared-snowplow-consumer/src/eventConsumer/userEvents/userEventConsumer.spec.ts
servers/user-api/src/context.ts
servers/user-api/src/test/functional/context.integration.ts
servers/user-api/src/test/functional/mutations-appleMigration.integration.ts
servers/user-api/src/test/functional/mutations-delete.integration.ts
servers/user-api/src/test/functional/mutations-updateEmail.integration.ts

Small fixes to support https://mozilla-hub.atlassian.net/browse/POCKET-9513
Main fix is https://github.com/Pocket/pocket-monorepo/pull/100

chore(tests): update test coverage of fxa

---

servers/list-api/src/dataService/listPaginationService.ts
servers/list-api/src/test/graphql/queries/savedItems.integration.ts

Fixes a bug where title was not returned on the graphql entity for paginated savedItems

fix(list): resolve title on pagination query

---

servers/shareable-lists-api/schema-public.graphql
servers/shareable-lists-api/src/database/index.ts
servers/shareable-lists-api/src/database/mutations/ShareableList.ts
servers/shareable-lists-api/src/database/mutations/ShareableListItem.ts
servers/shareable-lists-api/src/database/types.ts
servers/shareable-lists-api/src/public/resolvers/index.ts
servers/shareable-lists-api/src/public/resolvers/mutations/ShareableList.integration.ts
servers/shareable-lists-api/src/public/resolvers/mutations/ShareableList.ts
servers/shareable-lists-api/src/public/resolvers/mutations/sample-mutations.gql.ts

Create a new list and bulk-add to it in one mutation.
[POCKET-9504]
[POCKET-9504]: https://mozilla-hub.atlassian.net/browse/POCKET-9504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(shareable-lists): create and bulk add to shareable list

---

packages/terraform-modules/package.json

chore(release): removing dry run

---

pnpm-lock.yaml
turbo.json

Ensure that terraform-modules builds itself before releasing, by adding a depends on build

fix(build): ensuring the packages build themselves before releasing

---

.circleci/config.yml
packages/ts-logger/package.json

Found two typos, wrong value for the CI config and a forgotten `semantic-release` command

fix(bugs): fix typos

---

infrastructure/user-list-search/apollo_codedeploy.tf

Small fix to remove notifications to #pkt-alerts on start/success

fix(user-list-search): removing start/success notifications

---

packages/feature-flags-client/.eslintrc.js
packages/feature-flags-client/.npmignore
packages/feature-flags-client/README.md
packages/feature-flags-client/jest.config.js
packages/feature-flags-client/package.json
packages/feature-flags-client/src/index.spec.ts
packages/feature-flags-client/src/index.ts
packages/feature-flags-client/src/mockClient.ts
packages/feature-flags-client/tsconfig.json
pnpm-lock.yaml

Add feature flags client library and mock provider.
subtask for [POCKET-9478]
[POCKET-9478]: https://mozilla-hub.atlassian.net/browse/POCKET-9478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(feature-flags-client): add unleash client package

---

.circleci/common.yml
.circleci/user-list-search.yml
infrastructure/user-list-search/dev_backend.tfvars
infrastructure/user-list-search/locals.tf
infrastructure/user-list-search/prod_backend.tfvars
infrastructure/user-list-search/terraform.tf

Move userlistsearch to s3 state
https://mozilla-hub.atlassian.net/browse/POCKET-9563
https://github.com/Pocket/shared-infrastructure/pull/643

fix(user-list-search): moving user list search to s3 state

---

infrastructure/account-data-deleter/src/dataDeleterApp.ts

Add in access to the shared parameter

fix(account-deleter): update container to pull shared secret

---

.circleci/config.yml
.circleci/user-list-search.yml

fix(search): ensure search deploys to right ecs

---

docker-compose.yml
infrastructure/image-api/src/main.ts
infrastructure/parser-graphql-wrapper/src/main.ts

Clean up old caches https://mozilla-hub.atlassian.net/browse/POCKET-9596

chore(infra): cleaning up old image and parser cache

---

infrastructure/client-api/src/main.ts
infrastructure/shareable-lists-api/src/main.ts

Shutdown caches that are no longer in use

chore(cache): removing unused caches

---

servers/v3-proxy-api/src/generated/graphql/types.ts
servers/v3-proxy-api/src/graph/toGraphQL.spec.ts
servers/v3-proxy-api/src/graph/toGraphQL.ts
servers/v3-proxy-api/src/routes/validations.ts

Couldn't include this in the previous PR because of the code generation requiring a schema update.
[POCKET-9660]
[POCKET-9660]: https://mozilla-hub.atlassian.net/browse/POCKET-9660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(v3proxy): add video content type filter

---

lambdas/user-list-search-indexing/package.json
pnpm-lock.yaml

Forgot to include node fetch...

fix(node-fetch): including node fetch in lambda

---

infrastructure/user-list-search/locals.tf

fix(kinesis): update kinesis variables

---

servers/parser-graphql-wrapper/src/dataLoaders/itemLoader.integration.ts
servers/parser-graphql-wrapper/src/dataLoaders/itemLoader.ts

Ensure that we try to always respond with a valid item object for the clients.
In this case, items were returning from the Parser endpoint with a resolvedId of `0` and no data in their returned item object. However the top level response all contained data as expected.  It looks like in the parser there is a case where and item can resolve to another item, that does not self resolve. (ie itemId 1234 resolves to 123456 but, 123456 has a resolvedId of 0 when it should be `123456` (itself). 
The best way I could tell to fix this within our use case was to trigger a refresh of the item when that occurs.  This will cause the item to update its resolvedId to itself and the issue will self repair moving forward.

fix(item): ensuring that we resolve items if they are not there

---

lambdas/fxa-webook-proxy-sqs/src/config.ts
lambdas/fxa-webook-proxy-sqs/src/mutations.ts

Add in headers to identify the fxa webhook

fix(client): adding in client name for fxa

---

servers/v3-proxy-api/src/graph/get/toRest.spec.ts
servers/v3-proxy-api/src/graph/get/toRest.ts
servers/v3-proxy-api/src/graph/types.ts
servers/v3-proxy-api/src/main.ts
servers/v3-proxy-api/src/routes/v3Fetch.integration.ts
servers/v3-proxy-api/src/routes/v3Fetch.ts
servers/v3-proxy-api/src/routes/v3Get.integration.ts
servers/v3-proxy-api/src/routes/validations/FetchSchema.ts
servers/v3-proxy-api/src/test/fixtures/fetch.ts
servers/v3-proxy-api/src/test/fixtures/index.ts

Make fetch happen.
Add in the /v3/fetch api that is used by Android to load a users list initially.

feat(fetch): adding in the v3/fetch api initial response

---

servers/v3-proxy-api/src/routes/v3Get.integration.ts
servers/v3-proxy-api/src/routes/validations/GetSchema.ts

Make sure that since is always converted to an integer

fix(since): ensuring that since is converted to a number

---

infrastructure/account-data-deleter/src/dataDeleterApp.ts
infrastructure/annotations-api/src/main.ts
infrastructure/client-api/src/main.ts
infrastructure/feature-flags/src/main.ts
infrastructure/image-api/src/main.ts
infrastructure/list-api/src/main.ts
infrastructure/parser-graphql-wrapper/src/main.ts
infrastructure/shareable-lists-api/src/main.ts
infrastructure/shared-snowplow-consumer/src/sharedSnowplowConsumerApp.ts
infrastructure/user-api/src/main.ts
infrastructure/user-list-search/apollo_ecs.tf

Forgot to remove appspec in https://github.com/Pocket/pocket-monorepo/pull/324

fix(appspec): removing appsepc generation

---

infrastructure/annotations-api/src/main.ts
infrastructure/sendgrid-data/src/main.ts
servers/account-data-deleter/package.json
servers/account-data-deleter/src/batchDeleteHandler.spec.ts
servers/account-data-deleter/src/batchDeleteHandler.ts
servers/account-data-deleter/src/dataService/accountDeleteDataService.ts
servers/account-data-deleter/src/dataService/stripeDataDeleter.ts
servers/account-data-deleter/src/logger.ts
servers/account-data-deleter/src/routes/queueDelete.ts
servers/account-data-deleter/src/server.ts

Account data deleter was crashing because unleashClient was init'd too late in the BatchDataHandler

fix(account): ensuring account deleter runs

---

servers/push-server/src/apns.ts

Forgot to use the options i built

fix(notifcation): updating to use options

---

servers/v3-proxy-api/src/routes/validations/SendActionValidators.ts
servers/v3-proxy-api/src/routes/validations/sendActionValidators.spec.ts

[POCKET-9872]
[POCKET-9872]: https://mozilla-hub.atlassian.net/browse/POCKET-9872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(v3proxy:send): accept null item_id/url, as long as one is valid

---

servers/v3-proxy-api/src/routes/v3Fetch.integration.ts
servers/v3-proxy-api/src/routes/v3Fetch.ts

[POCKET-9897]
[POCKET-9897]: https://mozilla-hub.atlassian.net/browse/POCKET-9897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(v3proxy:fetch): request 'unread' items only from fetch

---

servers/parser-graphql-wrapper/src/dataLoaders/itemLoader.integration.ts
servers/parser-graphql-wrapper/src/dataLoaders/itemLoader.ts
servers/parser-graphql-wrapper/src/datasources/parserApi.integration.ts
servers/parser-graphql-wrapper/src/marticle/marticleParser.integration.ts
servers/parser-graphql-wrapper/src/refreshMutation.integration.ts
servers/parser-graphql-wrapper/src/resolvers.spec.ts
servers/parser-graphql-wrapper/src/shortUrl/shortUrl.integration.ts
servers/parser-graphql-wrapper/src/ssml/ssml.integration.ts
servers/parser-graphql-wrapper/src/timeToRead/timeToRead.integration.ts

[POCKET-9888]
[POCKET-9888]: https://mozilla-hub.atlassian.net/browse/POCKET-9888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(parser): use fallback option for better item_id resolution

---

infrastructure/instant-sync-events/src/config/index.ts
infrastructure/instant-sync-events/src/sqsEventLambda.ts
lambdas/instant-sync-events/src/clients.ts
lambdas/instant-sync-events/src/handlerFn.integration.ts
lambdas/instant-sync-events/src/handlerFn.ts

Instant sync should clean up its database connection when it is done with it.
Also a few lambda extension fixes

fix(instant-sync): instant sync fixes

---

infrastructure/parser-graphql-wrapper/src/main.ts

Lower costs of the parser graphql wrapper redis by limiting the serverless cache to 7GB. This must be done as a new cache, because of how terraform works with serverless redis.

fix(cache): moving to a much lower serverless redis cache

---

infrastructure/parser-graphql-wrapper/src/main.ts

Remove the elasticache created last month for a smaller more limited one. We have already switched over, this just cleans up the infra.

chore(elasticache): removes an older elasticache for a smaller more limited one

---

servers/parser-graphql-wrapper/src/resolvers.ts
servers/v3-proxy-api/src/generated/graphql/types.ts

First try and resolve by url before resolving by itemId

fix(parser): resolving by url first before itemId

---

servers/parser-graphql-wrapper/src/dataLoaders/itemLoader.integration.ts
servers/parser-graphql-wrapper/src/dataLoaders/itemLoader.ts

Use top-level fields provided by https://github.com/Pocket/Parser/pull/333

fix(parser): improve itemId accuracy

---

.circleci/common.yml
Dockerfile

PNPM 9 seems a bit buggy at the moment, so lets lock to 8

fix(pnpm): lock pnpm to 8

---

servers/parser-graphql-wrapper/src/apollo/resolvers.ts

Accidental copy pasta error from https://github.com/Pocket/pocket-monorepo/pull/474

fix(itemId): fix item id loader

---

servers/list-api/schema.graphql
servers/list-api/src/dataService/listPaginationService.ts
servers/list-api/src/test/graphql/queries/savedItems-filters-offset.integration.ts
servers/list-api/src/test/graphql/queries/savedItems-filters.integration.ts
servers/list-api/src/types/index.ts

To support Android access patterns for sync.
[POCKET-9896]
[POCKET-9896]: https://mozilla-hub.atlassian.net/browse/POCKET-9896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(list): add updatedBefore filter

---

servers/v3-proxy-api/src/generated/graphql/types.ts
servers/v3-proxy-api/src/graph/get/toGraphQL.spec.ts
servers/v3-proxy-api/src/graph/get/toGraphQL.ts
servers/v3-proxy-api/src/routes/v3Fetch.ts
servers/v3-proxy-api/src/routes/validations/GetSchema.ts

Supports Android sync patterns
[POCKET-9896]
[POCKET-9896]: https://mozilla-hub.atlassian.net/browse/POCKET-9896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(v3proxy): add updatedBefore option to fetch and get

---

servers/user-api/src/dataService/userDataService.ts
servers/user-api/src/test/functional/user.integration.ts

Fixes the SQL query for returning premium subscription (see comments for explanation).
[POCKET-9980]
[POCKET-9980]: https://mozilla-hub.atlassian.net/browse/POCKET-9980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(user): fix query for retrieving premium active status

---

packages/tracing/package.json
pnpm-lock.yaml

release tracing library for the content team

feat(tracing): releasing the tracing library

---

infrastructure/parser-graphql-wrapper/src/main.ts

fix(parser): removing duplicate secret

---

servers/parser-graphql-wrapper/src/datasources/parserApiUtils.ts

Fix a few sentry errors  re NaN and author id.
https://pocket.sentry.io/issues/5239911166/?environment=production&project=5591912&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=30d&stream_index=0
https://pocket.sentry.io/issues/4123589850/?environment=production&project=5591912&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=30d&stream_index=1

fix(parser): parsing the int value correctly

---

servers/v3-proxy-api/src/routes/validations/SendActionValidators.ts
servers/v3-proxy-api/src/routes/validations/sendActionValidators.spec.ts

fix: allow nullish title to pass validation but ignore

---

infrastructure/parser-graphql-wrapper/src/main.ts

clean up the old serverless cache

chore(parser): clean up the old parser serverless cache

---

servers/v3-proxy-api/src/graph/get/toRest.ts
servers/v3-proxy-api/src/routes/v3Get.integration.ts
servers/v3-proxy-api/src/test/fixtures/get-account.ts

Fixes bug where attempting to iterate over null resulted in internal server error.
[POCKET-10002]
[POCKET-10002]: https://mozilla-hub.atlassian.net/browse/POCKET-10002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(proxy): free account returns empty array for premium features

---

servers/parser-graphql-wrapper/schema.graphql
servers/parser-graphql-wrapper/src/__generated__/resolvers-types.ts
servers/parser-graphql-wrapper/src/apollo/resolvers.ts
servers/parser-graphql-wrapper/src/test/queries/preview.integration.ts
servers/v3-proxy-api/src/generated/graphql/types.ts

Switching to a pocket metadata interface to allow us to do more in the future

feat(metadata): adding a pocket metadata interface

---

servers/parser-graphql-wrapper/schema.graphql
servers/parser-graphql-wrapper/src/__generated__/resolvers-types.ts
servers/parser-graphql-wrapper/src/databases/itemSummaryStore.ts
servers/parser-graphql-wrapper/src/models/ItemSummaryModel.ts
servers/parser-graphql-wrapper/src/test/queries/preview.integration.ts

Move the remaining ItemSummary to `PocketMetadata`

fix(metadata): moving item summary to pocket metadata

---

servers/parser-graphql-wrapper/schema.graphql
servers/parser-graphql-wrapper/src/__generated__/resolvers-types.ts
servers/parser-graphql-wrapper/src/databases/itemSummaryStore.ts
servers/parser-graphql-wrapper/src/models/ItemSummaryModel.ts
servers/parser-graphql-wrapper/src/test/queries/preview.integration.ts

Reverts Pocket/pocket-monorepo#516

Revert "fix(metadata): moving item summary to pocket metadata"

---

servers/parser-graphql-wrapper/schema.graphql
servers/parser-graphql-wrapper/src/__generated__/resolvers-types.ts
servers/parser-graphql-wrapper/src/databases/itemSummaryStore.ts
servers/parser-graphql-wrapper/src/models/ItemSummaryModel.ts
servers/parser-graphql-wrapper/src/test/queries/preview.integration.ts

Reverts Pocket/pocket-monorepo#520

Revert "Revert "fix(metadata): moving item summary to pocket metadata""

---

pnpm-lock.yaml
servers/user-list-search/schema.graphql
servers/user-list-search/src/datasource/MysqlDataSource.ts
servers/user-list-search/src/datasource/elasticsearch/elasticsearchSearch.ts
servers/user-list-search/src/operations.ts
servers/user-list-search/src/recentSearches.integration.ts
servers/user-list-search/src/resolvers.ts

Mutation to save a search to 'recent searches'
Only applies to premium users.
[POCKET-10003]
[POCKET-10003]: https://mozilla-hub.atlassian.net/browse/POCKET-10003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(search): recent search mutation

---

packages/tracing/package.json
packages/tracing/src/tracing.ts
pnpm-lock.yaml
servers/annotations-api/src/main.ts
servers/list-api/src/server/main.ts
servers/user-api/src/main.ts
servers/user-list-search/src/main.ts

- opens up this package to services using prisma
i am lost without a PR template 🙃 
anything more y'all would like to see here? tests for constructing the instrumentation array? a push to dev?

feat: enable custom ORM tracing instrumentations per service

---

packages/tracing/src/tracing.ts

add a default value for `additionalInstrumentations`

fix(tracing): provide default value for additional instrumentation

---

servers/shares-api/schema.graphql
servers/shares-api/src/datasources/shares.ts
servers/shares-api/src/models/PocketShare.ts
servers/shares-api/src/test/addShareContext.integration.ts

Maintains the behavior where null data does nothing.
See tests for example behavior.
[POCKET-10088]
[POCKET-10088]: https://mozilla-hub.atlassian.net/browse/POCKET-10088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(shares): delete share context if empty data is passed

---

.syncpackrc
packages/apollo-utils/package.json
packages/backend-benchmarking/package.json
packages/feature-flags-client/package.json
packages/int-mask/package.json
packages/lambda-secrets/package.json
packages/sentry/package.json
packages/terraform-modules/package.json
packages/tracing/package.json
packages/ts-logger/package.json
pnpm-lock.yaml
servers/list-api/package.json

Fix tslib and ensure its always in prod deps

fix(tslib): ensuring tslib is always in prod deps

---

.circleci/common.yml
.circleci/scripts/setup.sh
.circleci/scripts/setup_aws.sh
.docker/aws-resources/account-data-deleter-batch-delete.sh
.docker/aws-resources/account-data-deleter.sh
.docker/aws-resources/account-delete-monitor.sh
.docker/aws-resources/annotations-api.sh
.docker/aws-resources/instant-sync-events.sh
.docker/aws-resources/list-api.sh
.docker/aws-resources/parser-graphql-wrapper.sh
.docker/aws-resources/shareable-lists-api.sh
.docker/aws-resources/shared-snowplow-consumer.sh
.docker/aws-resources/shares-api.sh
.docker/aws-resources/user-api.sh
README.md
pnpm-lock.yaml

Speed up our test integrations by only starting the services they need.
Basically if a service needs some aws stuff for integration testing, you give it a file that matches it's scope name and call the service creation that you need.

chore(scripts): making a script for each service to start their services

---

servers/annotations-api/src/models/HighlightsModel.ts
servers/v3-proxy-api/src/routes/ActionsRouter.ts

Fix POCKET-10130 which errors when you try and delete a highlight without a note on v3 proxy by catching errors on the note service

fix(annotations): catching errors on highlight notes

---

infrastructure/account-data-deleter/src/config/index.ts
infrastructure/account-delete-monitor/src/config/index.ts
infrastructure/annotations-api/src/config/index.ts
infrastructure/braze/src/config/index.ts
infrastructure/client-api/src/config/index.ts
infrastructure/feature-flags/src/config/index.ts
infrastructure/fxa-webhook-proxy/src/config/index.ts
infrastructure/image-api/src/config/index.ts
infrastructure/instant-sync-events/src/config/index.ts
infrastructure/list-api/src/config/index.ts
infrastructure/parser-graphql-wrapper/src/config/index.ts
infrastructure/pocket-event-bridge/src/config/index.ts
infrastructure/push-server/src/config/index.ts
infrastructure/sendgrid-data/src/config/index.ts
infrastructure/shareable-lists-api/src/config/index.ts
infrastructure/shared-snowplow-consumer/src/config/index.ts
infrastructure/shares-api/src/config/index.ts
infrastructure/transactional-emails/src/config/index.ts
infrastructure/user-api/src/config/index.ts
infrastructure/user-list-search/locals.tf
infrastructure/v3-proxy-api/src/config/index.ts

Add in new cost center tags that match SRE's tagging in GCP for costing
[POCKET-10138](https://mozilla-hub.atlassian.net/browse/POCKET-10138)
[POCKET-10138]: https://mozilla-hub.atlassian.net/browse/POCKET-10138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(costs): adding in cost center tags

---

.circleci/common.yml

Apply the fix from @jpetto https://github.com/Pocket/content-monorepo/pull/169/files#r1605128911

chore(pnpm): updating pnpm to use package scope

---

infrastructure/user-list-search/elasticsearch.tf

Deployed to dev. Deployment succeeded, and manual snapshot was created successfully (via python script).

feat(infra:search): infrastructure required for manual ES snapshots

---

infrastructure/user-list-search/backfill_item_update_consumer.tf
infrastructure/user-list-search/backfill_user_list_import_consumer.tf
infrastructure/user-list-search/corpus_events_consumer.tf
infrastructure/user-list-search/elasticsearch.tf
infrastructure/user-list-search/event_handler_consumer.tf
infrastructure/user-list-search/item_delete_consumer.tf
infrastructure/user-list-search/item_update_consumer.tf
infrastructure/user-list-search/user_list_import_consumer.tf

Migration to OpenSearch is complete, so let's restart the index process.

chore(search:infra): re-enable lambdas

---

lambdas/user-list-search-corpus-parser-hydration/src/parserRequest.ts
lambdas/user-list-search-corpus-parser-hydration/src/types.ts

These are camelCased, not snake_cased like others
Fixes not having a parent type for content.
[POCKET-10210]
[POCKET-10210]: https://mozilla-hub.atlassian.net/browse/POCKET-10210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(corpus search): correct fields for isArticle/isIndex

---

servers/v3-proxy-api/src/routes/ActionsRouter.ts
servers/v3-proxy-api/src/routes/v3Send.integration.ts

Missed a code path in #608 
[POCKET-10240]
[POCKET-10240]: https://mozilla-hub.atlassian.net/browse/POCKET-10240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(v3proxy): fix undefined default error

---

servers/v3-proxy-api/src/server.ts

For better observability, more information

feat(sentry): setup sentry context

---

infrastructure/user-list-search/elasticsearch.tf

Update terraform opensearch version record to match what is actually in AWS. 
Deployed to dev (matched the infrastructure).

chore(infra): update opensearch version

---

packages/sentry/src/initSentry.ts

Reverts Pocket/pocket-monorepo#615

Revert "fix(sentry): ensuring integrations are added to sentry"

---

.github/workflows/publish.yml

Fix failing setup step
Ref: https://github.com/pnpm/action-setup/issues/135

chore(deps): upgrade pnpm action-setup to v4

---

packages/tracing/src/tracing.ts
servers/list-api/src/config/index.ts
servers/parser-graphql-wrapper/src/config/index.ts
servers/shared-snowplow-consumer/src/config/index.ts

Lower our XRay sampling ratio to 1% to avoid AWS quota limits

fix(sampling): lowering our sampling ratio

---

infrastructure/account-data-deleter/src/dataDeleterApp.ts
infrastructure/annotations-api/src/main.ts
infrastructure/client-api/src/main.ts
infrastructure/feature-flags/src/main.ts
infrastructure/image-api/src/main.ts
infrastructure/list-api/src/config/index.ts
infrastructure/list-api/src/main.ts
infrastructure/parser-graphql-wrapper/src/config/index.ts
infrastructure/parser-graphql-wrapper/src/main.ts
infrastructure/push-server/src/main.ts
infrastructure/shared-snowplow-consumer/src/sharedSnowplowConsumerApp.ts
infrastructure/shares-api/src/main.ts
infrastructure/user-api/src/main.ts
servers/annotations-api/src/main.ts
servers/client-api/config/router.yaml
servers/image-api/src/server/main.ts
servers/list-api/src/server/main.ts
servers/parser-graphql-wrapper/src/main.ts
servers/shared-snowplow-consumer/src/main.ts
servers/shares-api/src/main.ts
servers/user-api/src/main.ts
servers/user-list-search/src/main.ts
servers/v3-proxy-api/src/main.ts

The content folks discovered that OTEL was increasing CPU/Mem usage. 
Since we have Sentry which supports OTEL and other investigation means, this removes OTEL for the time being as it seems to now be competing with how Sentry is setup.

fix(otel): removing otel

---

.github/workflows/account-data-deleter.yml
.github/workflows/account-delete-monitor.yml
.github/workflows/annotations-api.yml
.github/workflows/braze.yml
.github/workflows/client-api.yml
.github/workflows/feature-flags.yml
.github/workflows/fxa-webhook-proxy.yml
.github/workflows/image-api.yml
.github/workflows/instant-sync-events.yml
.github/workflows/list-api.yml
.github/workflows/parser-graphql-wrapper.yml
.github/workflows/pocket-event-bridge.yml
.github/workflows/push-server.yml
.github/workflows/sendgrid-data.yml
.github/workflows/shareable-lists-api.yml
.github/workflows/shared-snowplow-consumer.yml
.github/workflows/shares-api.yml
.github/workflows/transactional-emails.yml
.github/workflows/user-api.yml
.github/workflows/user-list-search.yml
.github/workflows/v3-proxy-api.yml

Updating paths for pushing envs

fix(ci): adding in push paths

---

.github/actions/ecs-codedeploy/action.yml

We need to replace appspec not append it.

fix(appends): ensure we replace files

---

.github/workflows/publish.yml

fix(release): updating token for release

---

.github/workflows/publish.yml
renovate.json

Update env for semantic release to publish

fix(token): adding in more env for GHA

---

turbo.json

See if passing the env via globalEnv makes them appear

fix(token): add tokens to env

---

infrastructure/fxa-webhook-proxy/src/sqsLambda.ts

fix(secrets): add lambda secret layer

---

.gitignore
lambdas/user-list-search-corpus-parser-hydration/package.json
lambdas/user-list-search-corpus-parser-hydration/src/embeddingsRequest.ts
pnpm-lock.yaml
scripts/explore-corpus-backfill/backfill-corpus.ipynb

Backfill script and added delays to lambdas to handle throttled

feat(search): corpus search backfill pipeline

---

infrastructure/user-list-search/corpus-embeddings/opensearch.tf

See: https://github.com/hashicorp/terraform-provider-aws/issues/25712

fix(infra): opensearch rollback workaround

---

lambdas/user-list-search-corpus-indexing/src/index.ts

#722 but also for user-list-search-corpus-indexing

rfix(logging): rename serverLogger data key

---

lambdas/user-list-search-corpus-parser-hydration/src/config.ts
lambdas/user-list-search-corpus-parser-hydration/src/index.ts

Enable/disable depending on language index.

fix(corpus search): language-specific embedding rules

---

lambdas/user-list-search-corpus-parser-hydration/package.json
lambdas/user-list-search-corpus-parser-hydration/src/embeddingsRequest.ts
pnpm-lock.yaml

Reduce connection overhead by reusing connections.
Bump timeouts to try to avoid more TimeoutErrors

chore(corpus search): update http options for sagemaker client

---

infrastructure/list-api/src/config/index.ts
infrastructure/list-api/src/main.ts
infrastructure/parser-graphql-wrapper/src/config/index.ts
infrastructure/parser-graphql-wrapper/src/main.ts

Update our databases from serverless v1 in dev to avoid extra AWS charges

fix(rds): update rds on dev

---

infrastructure/user-list-search/ecs_iam.tf
infrastructure/user-list-search/elasticsearch.tf

Assign to the correct task role
[POCKET-10558]
[POCKET-10558]: https://mozilla-hub.atlassian.net/browse/POCKET-10558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(infra): fix perms for putting events on event bridge

---

servers/parser-graphql-wrapper/schema.graphql
servers/parser-graphql-wrapper/src/__generated__/resolvers-types.ts
servers/parser-graphql-wrapper/src/apollo/resolvers.ts

[POCKET-10598]
[POCKET-10598]: https://mozilla-hub.atlassian.net/browse/POCKET-10598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(syndication): link Item to SyndicatedArticle entity

---

servers/image-api/schema.graphql

Make the description a bit better for @collectedmind  ;) 
_all good jest_

docs(description): making id more clear in image api

---

packages/feature-flags-client/package.json
pnpm-lock.yaml
servers/account-data-deleter/package.json
servers/braze-content-proxy/src/generated/graphql/types.ts
servers/feature-flags/package.json
servers/feature-flags/src/main.ts
servers/list-api/package.json
servers/user-list-search/package.json
servers/user-list-search/src/__generated__/types.ts
servers/v3-proxy-api/src/generated/graphql/types.ts

chore(unleash): update unleash

---

infrastructure/pocket-event-bridge/src/event-rules/search-api-events/eventConfig.ts
servers/shared-snowplow-consumer/src/eventConsumer/searchEvents/searchEventconsumer.ts
servers/shared-snowplow-consumer/src/snowplow/search/searchHandler.integration.ts
servers/shared-snowplow-consumer/src/snowplow/search/searchHandler.ts

Addresses https://pocket.sentry.io/issues/5871103503/?project=6704387&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0

fix(snowplow): search response rule detail type

---

servers/feature-flags/src/graphql/resolvers.ts

Reverts Pocket/pocket-monorepo#743
we think this is preventing content from showing up on home

Revert "feat(variants): support the new variants in unleash"

---

servers/feature-flags/src/graphql/resolvers.ts

Reverts Pocket/pocket-monorepo#747

Revert "Revert "feat(variants): support the new variants in unleash""

---

infrastructure/account-data-deleter/src/dataDeleterApp.ts
infrastructure/annotations-api/src/main.ts
infrastructure/braze-content-proxy/src/main.ts
infrastructure/braze/src/emailSendDomain.ts
infrastructure/client-api/src/main.ts
infrastructure/feature-flags/src/main.ts
infrastructure/image-api/src/main.ts
infrastructure/list-api/src/main.ts
infrastructure/parser-graphql-wrapper/src/main.ts
infrastructure/push-server/src/main.ts
infrastructure/shareable-lists-api/src/main.ts
infrastructure/shared-snowplow-consumer/src/sharedSnowplowConsumerApp.ts
infrastructure/shares-api/src/main.ts
infrastructure/user-api/src/main.ts
infrastructure/v3-proxy-api/src/main.ts
packages/apollo-utils/package.json
packages/image-utils/package.json
packages/jwt-utils/package.json
packages/lambda-secrets/package.json
packages/terraform-modules/package.json
packages/tracing/package.json
packages/ts-logger/package.json
packages/tsconfig/cdktf.json
turbo.json

Add strict null checks for all the infra packages
Also added a publish config for NPM which i noticed npm package deploys were failing without

chore(strictNull): adding strict null check to all infra

---

lambdas/user-list-search-corpus-parser-hydration/src/index.ts
lambdas/user-list-search-corpus-parser-hydration/src/utils.spec.ts
lambdas/user-list-search-corpus-parser-hydration/src/utils.ts

Typo in the boolean logic so I pulled it out and properly spec tested...

fix: boolean logic bugfix for embeddings logic

---

servers/account-data-deleter/src/batchDeleteHandler.ts
servers/account-data-deleter/src/config/tables.ts
servers/account-data-deleter/src/dataService/stripeDataDeleter.ts
servers/account-data-deleter/src/routes/queueDelete.integration.ts
servers/account-data-deleter/src/routes/queueDelete.ts
servers/account-data-deleter/tsconfig.json
servers/v3-proxy-api/src/generated/graphql/types.ts

Add in strict null for account data deleter

fix(strictNull): adding strict null for account data deleter

---

scripts/dedupe-historical-syndication/deduplicate_syndication.ipynb

[POCKET-10616]
[POCKET-10616]: https://mozilla-hub.atlassian.net/browse/POCKET-10616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(corpus:search): add syndication deduplication script

---

servers/list-api/src/server/main.ts
servers/parser-graphql-wrapper/src/main.ts
servers/v3-proxy-api/src/main.ts

fix(tracing): sentry sampling

---

servers/list-api/src/server/main.ts
servers/parser-graphql-wrapper/src/main.ts
servers/v3-proxy-api/src/main.ts

Reverts Pocket/pocket-monorepo#774

Revert "fix(tracing): sentry sampling"

---

servers/v3-proxy-api/src/server.ts

Move the priority of our sentry middleware

fix(sentry): update route priority

---

packages/apollo-utils/src/sentry/expressSentryMiddleware.ts
servers/annotations-api/src/server/index.ts
servers/parser-graphql-wrapper/src/apollo/server.ts
servers/shares-api/src/apollo/server.ts
servers/user-list-search/src/server/serverUtils.ts

Update all our services to add sentry tags before routes.
Also switching the ip address header to be lowercase since express lowercases all headers

fix(sentry): update sentry middleware initialization

---

packages/sentry/package.json
packages/sentry/src/featureFlagTraceSampler.ts
packages/sentry/src/index.ts
packages/sentry/src/initSentry.ts
pnpm-lock.yaml

See also: https://github.com/Pocket/pocket-ios/pull/721
[POCKET-10645]
[POCKET-10645]: https://mozilla-hub.atlassian.net/browse/POCKET-10645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(sentry): add feature flag sampler logic

---

infrastructure/v3-proxy-api/src/main.ts
pnpm-lock.yaml
servers/v3-proxy-api/package.json
servers/v3-proxy-api/src/config/index.ts
servers/v3-proxy-api/src/main.ts
servers/v3-proxy-api/src/unleash.ts

Allow v3 proxy to send sentry traces

fix(v3): adding in sentry sampler to v3 proxy

---

infrastructure/v3-proxy-api/src/main.ts

Allow v3 proxy to access param store

fix(ssm): adding in v3 proxy shared ssm access

---

servers/client-api/config/router.yaml
servers/v3-proxy-api/src/graph/graphQLClient.ts

Add baggage header to be propagated through client-api

fix(tracing): propagate sentry headers manually in v3proxy

---

.vscode/launch.json
packages/tracing/src/tracing.ts
servers/otel-collector/otel-collector-config.yaml
servers/parser-graphql-wrapper/package.json
servers/parser-graphql-wrapper/tsconfig.json

Tweak our otel settings to be more performant.

fix(otel): adjusting otel processing settings

---

servers/otel-collector/otel-collector-config.yaml

fix(otel): updating to fix resource detection

---

infrastructure/pocket-event-bridge/src/event-rules/list-api-events/eventConfig.ts
infrastructure/pocket-event-bridge/src/event-rules/list-export-request-ready/eventConfig.ts
infrastructure/pocket-event-bridge/src/event-rules/list-export-request-ready/index.ts

cherry-picking file changes from #819 to avoid
issues with terraform dependencies not resolving
properly.
[POCKET-10669]
[POCKET-10669]: https://mozilla-hub.atlassian.net/browse/POCKET-10669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(export): events infrastructure for export

---

infrastructure/pocket-event-bridge/src/event-rules/list-export-request-ready/eventConfig.ts
infrastructure/pocket-event-bridge/src/event-rules/list-export-request-ready/index.ts
infrastructure/pocket-event-bridge/src/main.ts

Fix missing main reference to build Sns topic for export ready

fix(export): fix missing main reference

---

servers/account-data-deleter/src/dataService/listDataExportService.ts
servers/account-data-deleter/src/dataService/s3Service.ts
servers/account-data-deleter/src/queueHandlers/exportHandler.spec.ts
servers/account-data-deleter/src/queueHandlers/exportHandler.ts

More levels of nesting in the export queue than in the account delete queue -- add some extra processing to the handleMessage method.
Tested in dev.

fix(export): parsing the nested mesage data

---

servers/braze-content-proxy/src/generated/graphql/types.ts
servers/v3-proxy-api/src/graph/graphQLClient.ts

Trace down the root of v3 errors that are showing no errors but appear in sentry.

fix(logging): adding in logging to v3 errors

---

infrastructure/account-data-deleter/src/dataDeleterApp.ts
infrastructure/account-data-deleter/src/main.ts

Move bucket and object permissions to separate policies.

fix(export): bucket permissions

---

servers/client-api/config/router.yaml

Reverts Pocket/pocket-monorepo#831

Revert "fix(router): turning on router retries"

---

lambdas/transactional-emails/src/braze.ts
lambdas/transactional-emails/src/index.ts

For debugging transactional email list export

chore: update verbosity of logging and errors

---

servers/account-data-deleter/package.json

Forgot to update the start script for account data deleter

fix(start): updating start script for account data deleter

---

.vscode/launch.json
packages/tracing/README.md
pnpm-lock.yaml
servers/account-data-deleter/package.json
servers/account-data-deleter/src/config/index.ts
servers/account-data-deleter/src/queueHandlers/queueHandler.ts
servers/account-data-deleter/src/server.ts
servers/account-data-deleter/src/types.ts
servers/account-data-deleter/tsconfig.json

Update documentation in tracing package on how to
do local overrides for 100% sampling of traces.
Add launch scripts for attaching and launching
the ADD service.

feat(observability): group traces for background processes in ADD

---

lambdas/instant-sync-events/src/index.ts
lambdas/user-list-search-events/index.ts
packages/tracing/src/tracing.ts
servers/account-data-deleter/src/main.ts
servers/annotations-api/src/main.ts
servers/braze-content-proxy/src/main.ts
servers/feature-flags/src/main.ts
servers/image-api/src/server/main.ts
servers/list-api/src/server/main.ts
servers/otel-collector/otel-collector-config.yaml
servers/parser-graphql-wrapper/src/main.ts
servers/shareable-lists-api/src/main.ts
servers/shared-snowplow-consumer/src/main.ts
servers/shares-api/src/main.ts
servers/user-api/src/main.ts
servers/user-list-search/src/main.ts
servers/v3-proxy-api/src/main.ts

fix(metrics): update to deploy metrics

---

infrastructure/shared-snowplow-consumer/src/main.ts

See https://github.com/Pocket/pocket-monorepo/pull/851

fix(alarm): update dlq alarm logic (snowplow)

---

infrastructure/shares-api/src/config/index.ts
infrastructure/shares-api/src/main.ts

fix(otlp): ensuring shares api sends data

---

servers/v3-proxy-api/src/server.ts

Remove sentry middle ware on v3 proxy

fix(sentry): remove sentry middle ware for v3 proxy

---

lambdas/account-data-deleter-events/src/handlers/accountDelete/index.ts
lambdas/account-data-deleter-events/src/schemas/accountDeleteEvent.ts

isPremium can also be optional coming into this Lambda body.

fix(optional): making isPremium optional

---

docker-compose.yml
servers/client-api/config/router.yaml
servers/client-api/config/supergraph.yaml
servers/client-api/run_local.sh

Append v1/metrics to the routers otel sender, and add in some local testing scripts.

fix(router): ensuring we append v1/metrics

---

servers/client-api/config/router.yaml

Enable demand control measurement

fix(demandControl): adding in demand control

---

servers/client-api/config/router.yaml

Reverts Pocket/pocket-monorepo#876

Revert "fix(demandControl): adding in demand control"

---

infrastructure/account-data-deleter/src/config/index.ts

Update Account Deleter Historical to poll every 30 minutes

fix(accountDelete): speeding up account deleter historical

---

lambdas/instant-sync-events/package.json
lambdas/instant-sync-events/src/clients.ts
pnpm-lock.yaml

Use serverless knex for instant sync

fix(knex): serverless knex for instant sync

---

packages/event-bridge/src/events/types/accountDelete.spec.ts
packages/event-bridge/src/events/types/forgotPasswordRequest.spec.ts
packages/event-bridge/src/utils.ts

Web repo sends some bad types, lets allow some type coercion.
A future pr will look at using a serializer

fix(types): allowing type coeresion

---

lambdas/transactional-emails/src/handlers/forgotPassword.ts
packages/event-bridge/src/events/generated/schema.json
packages/event-bridge/src/events/types/forgotPasswordRequest.spec.ts
packages/event-bridge/src/events/types/forgotPasswordRequest.ts

Forgot password is actually a date time string in Web Repo..
https://github.com/Pocket/Web/blob/81ac897401a450796ee1a6a801de0f22b91d38c9/classes/Commands/PasswordReset.php#L156

fix(forgotpassword): updating the forgot password spec

---

servers/list-api/src/resolvers/mutation.ts
servers/list-api/src/resolvers/utils.ts
servers/list-api/src/test/graphql/mutations/savedItemById/savedItemsMutationService-upsert.integration.ts

Reject items that are files, ftp, tel links as a bad user input error
https://pocket.sentry.io/issues/5612403011/?project=5761820&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=24h&stream_index=3

fix(files): rejecting file and other invalid url types

---

servers/parser-graphql-wrapper/src/models/PocketMetadataModel.ts

Fix https://pocket.sentry.io/issues/5864601572/?project=5591912&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=11
https://mozilla-hub.atlassian.net/browse/POCKET-10774

fix(metadata): update metadata to allow null syndication images

---

servers/list-api/src/resolvers/mutation.ts

Use a feature flag to enable getting an upload link even if 24 hours has not passed

chore(import): override limit for testing with flag

---

servers/parser-graphql-wrapper/schema-admin.graphql
servers/parser-graphql-wrapper/schema.graphql
servers/parser-graphql-wrapper/src/__generated__/resolvers-types.ts
servers/parser-graphql-wrapper/src/datasources/parserApiUtils.ts
servers/parser-graphql-wrapper/src/marticle/marticleParser.ts

Add back in missing DailyMotion video id type https://github.com/Pocket/Parser/blob/ae1c363816e5d53e6ce5ad9d1bc7890fad9731b5/includes/v3beta/config.php#L55

fix(videos): updating video types for dailymotion

---

servers/v3-proxy-api/src/graph/graphQLClient.ts
servers/v3-proxy-api/src/routes/ActionsRouter.ts
servers/v3-proxy-api/src/routes/v3Add.integration.ts
servers/v3-proxy-api/src/routes/v3Add.ts

Ensure graphql proxy returns an unauthorized error

fix(v3-proxy): adding a possible error scenario that should be caught

---

servers/parser-graphql-wrapper/src/config/index.ts
servers/parser-graphql-wrapper/src/models/PocketMetadataModel.ts
servers/parser-graphql-wrapper/src/models/pocketMetadataModels/OEmbedModel.ts
servers/parser-graphql-wrapper/src/models/pocketMetadataModels/OpenGraphModel.ts

Enable oembed for all domains that it supports behind a flag.

fix(oembed): enable oembed behind a flag for all

---

packages/feature-flags-client/package.json
packages/sentry/package.json
pnpm-lock.yaml

Deploy feature flags and sentry for Content to use

feat(featureFlags/sentry): publishing feature flags client and sentry package

---

infrastructure/otel-collector/src/config/index.ts

Update the cost tags to share the otel collector as a shared cost

fix(otel): share the otel collector with content

---

servers/parser-graphql-wrapper/src/models/pocketMetadataModels/OpenGraphModel.ts

Ensure we try catch open graph results. In this case the end site was returning invalid json cause a throw.

fix(openGraph): ensuring we try catch open graph calls

---

packages/tracing/src/tracing.ts

Add the environment to the OTEL logger

fix(otel): adding in the environment to otel

---

infrastructure/shared-snowplow-consumer/src/main.ts

fix(sharedSnowplow): updating max receive count

---

infrastructure/shared-snowplow-consumer/src/main.ts

fix(sharedSnowplow): fixing dlq max receive count

---

packages/apollo-utils/.npmignore
packages/backend-benchmarking/.npmignore
packages/event-bridge/.npmignore
packages/event-bridge/package.json
packages/feature-flags-client/.npmignore
packages/image-utils/.npmignore
packages/int-mask/.npmignore
packages/jwt-utils/.npmignore
packages/lambda-secrets/.npmignore
packages/sentry/.npmignore
packages/terraform-modules/.npmignore
packages/tracing/.npmignore
packages/ts-logger/.npmignore

Fix up package building.
Notably, forgot to add the presemantic-release build step to the event bridge package

fix(packages): updating package build bug

---

packages/apollo-utils/package.json
packages/event-bridge/package.json
packages/feature-flags-client/package.json
packages/image-utils/package.json
packages/jwt-utils/package.json
packages/lambda-secrets/package.json
packages/sentry/package.json
packages/terraform-modules/package.json
packages/tracing/package.json
packages/ts-logger/package.json

Use analyze commits which I believe has access to lastRelease

fix(semantic-release): using the analyzeCommits command which has the last release

---

packages/apollo-utils/package.json
packages/event-bridge/package.json
packages/feature-flags-client/package.json
packages/image-utils/package.json
packages/jwt-utils/package.json
packages/lambda-secrets/package.json
packages/sentry/package.json
packages/terraform-modules/package.json
packages/tracing/package.json
packages/ts-logger/package.json

Make sure semantic releases put in version numbers as required.

fix(semantic-release): ensuring all analyze commits return nothing

---

packages/apollo-utils/package.json
packages/event-bridge/package.json
packages/feature-flags-client/package.json
packages/image-utils/package.json
packages/jwt-utils/package.json
packages/lambda-secrets/package.json
packages/sentry/package.json
packages/terraform-modules/package.json
packages/tracing/package.json
packages/ts-logger/package.json

fix(semantic-release): ensure we set package versions

---

servers/account-data-deleter/src/dataService/listDataExportService.ts

Export events are keyed on account-data-deleter

fix(export): updating export event

---

servers/notes-api/schema.graphql
servers/notes-api/src/__generated__/graphql.d.ts
servers/notes-api/src/apollo/resolvers.ts
servers/notes-api/src/datasources/NoteService.ts
servers/notes-api/src/models/Note.ts
servers/notes-api/src/test/mutations/editNoteTitle.integration.ts
servers/notes-api/src/test/operations/mutations.ts

Mutation to edit the title of an existing note.
[POCKET-10863]
[POCKET-10863]: https://mozilla-hub.atlassian.net/browse/POCKET-10863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(notes): edit title of a note

---

servers/notes-api/schema.graphql
servers/notes-api/src/__generated__/graphql.d.ts
servers/notes-api/src/apollo/resolvers.ts
servers/notes-api/src/datasources/NoteService.ts
servers/notes-api/src/models/Note.ts
servers/notes-api/src/test/mutations/deleteNote.integration.ts
servers/notes-api/src/test/operations/mutations.ts
servers/notes-api/src/test/queries/note.integration.ts

[POCKET-10864]
[POCKET-10864]: https://mozilla-hub.atlassian.net/browse/POCKET-10864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(notes): delete a note

---

servers/notes-api/schema.graphql
servers/notes-api/src/__generated__/graphql.ts
servers/notes-api/src/apollo/resolvers.ts
servers/notes-api/src/datasources/NoteService.ts
servers/notes-api/src/models/Note.ts
servers/notes-api/src/test/mutations/archiveNote.integration.ts
servers/notes-api/src/test/mutations/unArchiveNote.integration.ts
servers/notes-api/src/test/operations/mutations.ts

Archive/unarchive note mutation
[POCKET-10867]
[POCKET-10867]: https://mozilla-hub.atlassian.net/browse/POCKET-10867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(notes): un/archive notes

---

servers/notes-api/codegen.ts
servers/notes-api/schema.graphql
servers/notes-api/src/__generated__/graphql.ts
servers/notes-api/src/apollo/resolvers.ts
servers/notes-api/src/datasources/NoteService.ts
servers/notes-api/src/models/Note.ts
servers/notes-api/src/models/SavedItem.ts
servers/notes-api/src/test/operations/queries.ts
servers/notes-api/src/test/queries/notes.integration.ts
servers/notes-api/src/test/queries/savedItem.integration.ts

Resolve notes from a SavedItem.
[POCKET-10867]
[POCKET-10867]: https://mozilla-hub.atlassian.net/browse/POCKET-10867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(notes): resolve notes from a SavedItem

---

.github/actions/build-lambda/action.yml
.github/actions/cdktf/action.yml
.github/workflows/reuse-apollo-federation.yml
.github/workflows/reuse-build-and-push-image.yml
.github/workflows/reuse-build-and-push-lambda.yml
.github/workflows/reuse-infrastructure.yml
.github/workflows/reuse-test-integrations.yml

Revert the relative changes, because it broke CI for the content team

fix(ci): put back the main repo pointer

---

servers/otel-collector/httpd.conf

fix(otel): allow larger otel size

---

servers/client-api/config/router.yaml

http.server.active_requests instrument does not support custom attributes; remove them

fix(router): otel config

---

servers/client-api/config/router.yaml
servers/client-api/run_local.sh

Fix subgraph document being sent

fix(otel): removing document body

---

servers/client-api/config/router.yaml

Add in attributes for active requests

fix(metrics): add in active request data

---

servers/client-api/config/router.yaml

Reverts Pocket/pocket-monorepo#1023

Revert "fix(metrics): add in active request data"

---

servers/otel-collector/otel-collector-config.yaml

Truncate logs to avoid hitting googles 256kb limit

fix(logs): ensure logs are truncated to 256kb

---

servers/notes-api/schema.graphql
servers/notes-api/src/__generated__/db.ts
servers/notes-api/src/__generated__/graphql.ts
servers/notes-api/src/datasources/NoteService.ts
servers/notes-api/src/test/mutations/editNoteTitle.integration.ts

If null is passed, sets title to null

feat(notes): allow null input for editNoteTitle

---

servers/account-data-deleter/src/dataService/listDataExportService.ts

Sometimes the title gets saved as Problem loading page

feat: add additional fallback case for parser failure

---

infrastructure/account-data-deleter/src/dataDeleterApp.ts

Allow us to process a larger volume of data exports.

HNT-706: Scale out account data deleter
